return {
	root={
		background_color=255,
		background_type=1,
		border_width_bottom=1,
		border_width_left=1,
		border_width_right=1,
		border_width_top=1,
		children={
			{
				background_color=4278519137,
				background_type=1,
				border_width_bottom=1,
				border_width_left=1,
				border_width_right=1,
				border_width_top=1,
				h=39,
				span_count=1,
				text='abc',
				text_spans={
					{
						span_font='OpenSans-Regular.ttf',
						span_font_size=22
					}
				},
				w=85
			},
			{
				background_color=570482798,
				background_type=1,
				border_width_bottom=1,
				border_width_left=1,
				border_width_right=1,
				border_width_top=1,
				h=98,
				layout_type=1,
				padding_bottom=17.5,
				padding_left=17.5,
				padding_right=17.5,
				padding_top=17.5,
				span_count=1,
				text='xyz',
				text_spans={
					{
						span_font='Amiri-Regular.ttf',
						span_font_size=35
					}
				},
				w=82
			}
		},
		h=464,
		layout_type=1,
		min_cw=352.5,
		span_count=1,
		text='abcd \244\128\128\128 xyz\244\128\128\129123',
		text_cursor_count=1,
		text_cursors={
			{
				text_cursor_offset=2,
				text_cursor_sel_offset=2,
				text_cursor_x=101
			}
		},
		text_spans={
			{
				span_font='SourceHanSans.ttc',
				span_font_face_index=15,
				span_font_size=100
			}
		},
		w=352.5,
		x=100,
		y=100
	},
	selected_layer_path={
	},
	tab='Background'
}