#!/bin/sh
# luajit wrapper that can be called from Windows, Linux or OSX.
[ "$PROCESSOR_ARCHITECTURE" = "AMD64" -o "$PROCESSOR_ARCHITEW6432" = "AMD64" -o "$OSTYPE" = "msys" ] && platform=mingw32 || {
	[ "${OSTYPE#darwin}" != "$OSTYPE" ] && platform=osx32 || platform=linux32
}
exec "${0%luajit32}/bin/$platform/luajit" "$@"
