return {
	mingw64={
		affine2d={
			affine2d={
			}
		},
		amoeba={
			amoeba={
			}
		},
		bitmap={
			bitmap={
				autoloads={
					blend='bitmap_blend',
					blend_op='bitmap_blend',
					convolve='bitmap_effects',
					dither='bitmap_dither',
					grayscale='bitmap_effects',
					invert='bitmap_effects',
					mirror='bitmap_effects',
					resize='bitmap_resize',
					sharpen='bitmap_effects'
				},
				mdeps={
					bit=true,
					box2d=true,
					ffi=true,
					glue=true
				}
			},
			bitmap_blend={
				mdeps={
					bitmap=true,
					box2d=true
				}
			},
			bitmap_dither={
				mdeps={
					bitmap=true
				}
			},
			bitmap_effects={
				mdeps={
					bitmap=true
				}
			},
			bitmap_resize={
				mdeps={
					bitmap=true
				}
			},
			bitmap_rgbaf={
				mdeps={
					bitmap=true,
					ffi=true,
					glue=true
				}
			}
		},
		blake2={
			blake2={
				ffi_deps={
					blake2=true
				},
				mdeps={
					ffi=true
				}
			}
		},
		bmp={
			bmp={
				mdeps={
					bit=true,
					bitmap=true,
					ffi=true,
					glue=true
				}
			}
		},
		bnet={
			bnet={
				mdeps={
					bit=true,
					bnet_h=true,
					ffi=true
				}
			},
			bnet_h={
				ffi_deps={
					ws2_32=true
				},
				mdeps={
					ffi=true
				}
			}
		},
		box2d={
			box2d={
			}
		},
		boxblur={
			boxblur={
				ffi_deps={
					boxblur=true
				},
				mdeps={
					bitmap=true,
					ffi=true,
					glue=true
				}
			}
		},
		bundle={
			bundle={
				mdeps={
					bundle_appversion=true,
					ffi=true
				}
			},
			bundle_fs={
				mdeps={
					bundle=true,
					ffi=true,
					fs=true
				}
			},
			bundle_loader={
				mdeps={
					ffi=true
				}
			},
			bundle_luastate={
				mdeps={
					ffi=true,
					luastate=true
				}
			}
		},
		cairo={
			cairo={
				ffi_deps={
					cairo=true
				},
				mdeps={
					bit=true,
					cairo_h=true,
					ffi=true
				}
			},
			cairo_h={
				mdeps={
					ffi=true
				}
			},
			cairo_quartz={
				loaderr='platform not OSX'
			},
			cairo_quartz_h={
				loaderr='platform not OSX'
			},
			cairo_win32={
				mdeps={
					cairo=true,
					cairo_win32_h=true,
					ffi=true
				}
			},
			cairo_win32_h={
				mdeps={
					cairo_h=true,
					ffi=true,
					['winapi.logfonttype']=true,
					['winapi.types']=true
				}
			}
		},
		cbframe={
			cbframe={
				mdeps={
					cbframe_x86=true,
					dynasm=true
				}
			},
			cbframe_dump={
				mdeps={
					cbframe=true,
					ffi=true
				}
			},
			cbframe_x86={
				mdeps={
					cbframe_x86_h=true,
					dasm=true,
					dasm_mm=true,
					dasm_x64=true,
					ffi=true
				}
			},
			cbframe_x86_h={
				mdeps={
					ffi=true
				}
			}
		},
		cjson={
			cjson={
			}
		},
		['clang-resource-dir']={
		},
		clipper={
			clipper={
				ffi_deps={
					clipper=true
				},
				mdeps={
					ffi=true
				}
			}
		},
		codedit={
			codedit={
			}
		},
		color={
			color={
				mdeps={
					bit=true
				}
			}
		},
		coro={
			coro={
			}
		},
		cplayer={
			cplayer={
				autoloads={
					analog_clock='cplayer.analog_clock',
					button='cplayer.buttons',
					checkerboard='cplayer.checkerboard',
					circle='cplayer.theme',
					code_editor='cplayer.code_editor',
					combobox='cplayer.combobox',
					curve='cplayer.theme',
					dot='cplayer.theme',
					dragpoint='cplayer.dragpoint',
					dragpoints='cplayer.dragpoint',
					editbox='cplayer.editbox',
					filebox='cplayer.filebox',
					fill='cplayer.theme',
					fillstroke='cplayer.theme',
					grid='cplayer.grid',
					hscrollbar='cplayer.scrollbars',
					hsplitter='cplayer.splitter',
					hue_wheel='cplayer.hue_wheel',
					image='cplayer.image',
					label='cplayer.label',
					line='cplayer.theme',
					magnifier='cplayer.magnifier',
					mbutton='cplayer.buttons',
					menu='cplayer.menu',
					parse_color='cplayer.theme',
					parse_font='cplayer.theme',
					rect='cplayer.theme',
					sat_lum_square='cplayer.sat_lum_square',
					save_theme='cplayer.theme',
					screen='cplayer.screen',
					scrollbox='cplayer.scrollbars',
					setcolor='cplayer.theme',
					setfont='cplayer.theme',
					slider='cplayer.slider',
					stroke='cplayer.theme',
					tablist='cplayer.tablist',
					text='cplayer.text',
					textbox='cplayer.text',
					themes='cplayer.theme',
					togglebutton='cplayer.buttons',
					toolbox='cplayer.toolbox',
					treeview='cplayer.treeview',
					vscrollbar='cplayer.scrollbars',
					vsplitter='cplayer.splitter'
				},
				mdeps={
					box2d=true,
					cairo=true,
					['cplayer.layerlist']=true,
					['cplayer.rmgui']=true,
					glue=true,
					nw=true,
					time=true
				}
			},
			['cplayer.analog_clock']={
				mdeps={
					cplayer=true,
					easing=true,
					socket=true
				}
			},
			['cplayer.boxlayer']={
				mdeps={
					box2d=true,
					glue=true
				}
			},
			['cplayer.boxlayout']={
				mdeps={
					cplayer=true
				}
			},
			['cplayer.buttons']={
				mdeps={
					cplayer=true
				}
			},
			['cplayer.checkerboard']={
				mdeps={
					cplayer=true
				}
			},
			['cplayer.code_editor']={
				mdeps={
					cairo=true,
					codedit=true,
					cplayer=true,
					['cplayer.codedit_imgui']=true,
					freetype=true,
					glue=true,
					nw=true
				}
			},
			['cplayer.codedit_imgui']={
				mdeps={
					codedit=true
				}
			},
			['cplayer.combobox']={
				mdeps={
					cplayer=true
				}
			},
			['cplayer.dragpoint']={
				mdeps={
					cplayer=true
				}
			},
			['cplayer.editbox']={
				mdeps={
					cplayer=true,
					ffi=true
				}
			},
			['cplayer.filebox']={
				ffi_deps={
					Ole32=true
				},
				mdeps={
					cplayer=true,
					ffi=true,
					winapi=true,
					['winapi.filedialogs']=true
				}
			},
			['cplayer.forms']={
				mdeps={
					cplayer=true
				}
			},
			['cplayer.grid']={
				mdeps={
					cplayer=true,
					glue=true
				}
			},
			['cplayer.hue_wheel']={
				mdeps={
					color=true,
					cplayer=true,
					path2d_point=true
				}
			},
			['cplayer.image']={
				mdeps={
					bitmap=true,
					cairo=true,
					cplayer=true
				}
			},
			['cplayer.itemlist']={
				mdeps={
					box2d=true,
					cplayer=true
				}
			},
			['cplayer.itemlist2']={
				mdeps={
					box2d=true,
					cplayer=true
				}
			},
			['cplayer.itemlist3']={
				mdeps={
					box2d=true,
					cplayer=true
				}
			},
			['cplayer.label']={
				mdeps={
					cplayer=true,
					glue=true
				}
			},
			['cplayer.layerlist']={
			},
			['cplayer.magnifier']={
				mdeps={
					bitmap=true,
					cairo=true,
					cplayer=true,
					ffi=true
				}
			},
			['cplayer.menu']={
				mdeps={
					cplayer=true
				}
			},
			['cplayer.menubar']={
				mdeps={
					glue=true
				}
			},
			['cplayer.rmgui']={
				mdeps={
					box2d=true,
					['cplayer.layerlist']=true
				}
			},
			['cplayer.sat_lum_square']={
				mdeps={
					bitmap=true,
					box2d=true,
					cairo=true,
					color=true,
					cplayer=true
				}
			},
			['cplayer.screen']={
				mdeps={
					box2d=true,
					cplayer=true
				}
			},
			['cplayer.scrollbars']={
				mdeps={
					cplayer=true
				}
			},
			['cplayer.slider']={
				mdeps={
					cairo=true,
					cplayer=true
				}
			},
			['cplayer.splitter']={
				mdeps={
					cplayer=true
				}
			},
			['cplayer.tablist']={
				mdeps={
					cplayer=true,
					glue=true
				}
			},
			['cplayer.text']={
				mdeps={
					cplayer=true,
					ffi=true,
					glue=true
				}
			},
			['cplayer.theme']={
				mdeps={
					color=true,
					cplayer=true,
					ffi=true,
					glue=true
				}
			},
			['cplayer.toolbox']={
				mdeps={
					box2d=true,
					cplayer=true
				}
			},
			['cplayer.treeview']={
				mdeps={
					cplayer=true
				}
			}
		},
		dynasm={
			dasm={
				ffi_deps={
					dasm_x86=true
				},
				mdeps={
					bit=true,
					ffi=true
				}
			},
			dasm_mm={
				mdeps={
					ffi=true
				}
			},
			dasm_x64={
				mdeps={
					dasm_x86x64=true
				}
			},
			dasm_x86={
				mdeps={
					dasm_x86x64=true
				}
			},
			dasm_x86x64={
			},
			dynasm={
			}
		},
		easing={
			easing={
			}
		},
		eq={
			eq={
			}
		},
		events={
			events={
			}
		},
		expat={
			expat={
				ffi_deps={
					expat=true
				},
				mdeps={
					expat_h=true,
					ffi=true,
					glue=true
				}
			},
			expat_h={
				mdeps={
					ffi=true
				}
			}
		},
		ffi_reflect={
			ffi_reflect={
				mdeps={
					bit=true,
					ffi=true
				}
			}
		},
		font_db={
			font_db={
				mdeps={
					glue=true
				}
			}
		},
		['fonts-amiri']={
		},
		['fonts-awesome']={
		},
		['fonts-dejavuserif']={
		},
		['fonts-fireflysung']={
		},
		['fonts-fixedsys']={
		},
		['fonts-ionicons']={
		},
		['fonts-material-icons']={
		},
		['fonts-noto-emoji']={
		},
		['fonts-open-sans']={
		},
		freetype={
			freetype={
				ffi_deps={
					freetype=true
				},
				mdeps={
					bit=true,
					ffi=true,
					freetype_h=true
				}
			},
			freetype_h={
				mdeps={
					ffi=true
				}
			}
		},
		fribidi={
			fribidi={
				ffi_deps={
					fribidi=true
				},
				mdeps={
					bit=true,
					ffi=true,
					fribidi_h=true
				}
			},
			fribidi_h={
				mdeps={
					ffi=true
				}
			}
		},
		fs={
			fs={
				mdeps={
					ffi=true,
					fs_common=true,
					fs_win=true
				}
			},
			fs_common={
				mdeps={
					bit=true,
					ffi=true,
					path=true
				}
			},
			fs_posix={
				loaderr='platform not Linux or OSX'
			},
			fs_win={
				mdeps={
					bit=true,
					ffi=true,
					fs_common=true
				}
			}
		},
		genx={
			genx={
				ffi_deps={
					genx=true
				},
				mdeps={
					ffi=true,
					genx_h=true
				}
			},
			genx_h={
				mdeps={
					ffi=true
				}
			}
		},
		gfonts={
			gfonts={
				mdeps={
					fs=true,
					glue=true,
					pp=true
				}
			}
		},
		giflib={
			giflib={
				ffi_deps={
					gif=true
				},
				mdeps={
					ffi=true,
					giflib_h=true,
					glue=true
				}
			},
			giflib_h={
				mdeps={
					ffi=true
				}
			}
		},
		glue={
			glue={
				mdeps={
					ffi=true
				}
			}
		},
		harfbuzz={
			harfbuzz={
				ffi_deps={
					harfbuzz=true
				},
				mdeps={
					bit=true,
					ffi=true,
					harfbuzz_h=true
				}
			},
			harfbuzz_h={
				mdeps={
					ffi=true
				}
			}
		},
		hash_benchmark={
		},
		heap={
			heap={
			}
		},
		hidapi={
			hidapi={
				ffi_deps={
					hidapi=true
				},
				mdeps={
					ffi=true,
					winapi=true
				}
			}
		},
		hmac={
			hmac={
				autoloads={
				},
				mdeps={
					bit=true,
					ffi=true,
					glue=true
				}
			}
		},
		hunspell={
			hunspell={
				ffi_deps={
					hunspell=true
				},
				mdeps={
					ffi=true
				}
			}
		},
		inspect={
			inspect={
			}
		},
		lanes={
			lanes={
				mdeps={
					['lanes.core']=true
				}
			},
			['lanes.core']={
			}
		},
		lexer={
			lexer={
				mdeps={
					lpeg=true
				}
			}
		},
		lfrb={
			lfrb={
				ffi_deps={
					lfrb=true
				},
				mdeps={
					ffi=true
				}
			}
		},
		lfs={
			lfs={
			}
		},
		libb64={
			libb64={
				ffi_deps={
					b64=true
				},
				mdeps={
					ffi=true
				}
			}
		},
		libcurl={
			libcurl={
				ffi_deps={
					curl=true
				},
				mdeps={
					bit=true,
					ffi=true,
					libcurl_h=true
				}
			},
			libcurl_h={
				mdeps={
					ffi=true
				}
			}
		},
		libexif={
			libexif={
				ffi_deps={
					exif=true
				},
				mdeps={
					ffi=true,
					libexif_h=true
				}
			},
			libexif_h={
				mdeps={
					ffi=true
				}
			}
		},
		libjpeg={
			libjpeg={
				ffi_deps={
					jpeg=true
				},
				mdeps={
					bit=true,
					ffi=true,
					glue=true,
					jit=true,
					libjpeg_h=true
				}
			},
			libjpeg_h={
				mdeps={
					ffi=true
				}
			}
		},
		libmariadb={
		},
		libmysql={
		},
		libogg={
			libogg_h={
				mdeps={
					ffi=true
				}
			}
		},
		libpng={
			libpng={
				ffi_deps={
					png=true
				},
				mdeps={
					bit=true,
					ffi=true,
					glue=true,
					jit=true,
					libpng_h=true
				}
			},
			libpng_h={
				mdeps={
					ffi=true
				}
			}
		},
		libsodium={
			libsodium={
				ffi_deps={
					sodium=true
				},
				mdeps={
					ffi=true,
					libsodium_h=true
				}
			},
			libsodium_h={
				mdeps={
					ffi=true
				}
			}
		},
		libsoundio={
			libsoundio={
				ffi_deps={
					soundio=true
				},
				mdeps={
					ffi=true,
					libsoundio_h=true
				}
			},
			libsoundio_h={
				mdeps={
					ffi=true
				}
			}
		},
		libstdcxx={
		},
		libunibreak={
			libunibreak={
				ffi_deps={
					unibreak=true
				},
				mdeps={
					ffi=true,
					libunibreak_h=true
				}
			},
			libunibreak_h={
				mdeps={
					ffi=true
				}
			}
		},
		linkedlist={
			linkedlist={
			}
		},
		llvm={
			llvm={
				ffi_deps={
					llvm=true
				},
				mdeps={
					ffi=true,
					glue=true,
					llvm_h=true
				}
			},
			llvm_h={
				mdeps={
					ffi=true
				}
			}
		},
		lpeg={
			lpeg={
			},
			['lpeg.re']={
				mdeps={
					lpeg=true
				}
			}
		},
		lrucache={
			lrucache={
				mdeps={
					linkedlist=true
				}
			}
		},
		['lua-headers']={
		},
		luajit={
			_G={
			},
			bit={
			},
			coroutine={
			},
			debug={
			},
			ffi={
			},
			io={
			},
			jit={
			},
			['jit.bc']={
				mdeps={
					bit=true,
					jit=true,
					['jit.util']=true,
					['jit.vmdef']=true
				}
			},
			['jit.bcsave']={
				mdeps={
					bit=true,
					jit=true
				}
			},
			['jit.dis_x64']={
				mdeps={
					['jit.dis_x86']=true
				}
			},
			['jit.dis_x86']={
				mdeps={
					bit=true
				}
			},
			['jit.dump']={
				mdeps={
					bit=true,
					jit=true,
					['jit.util']=true,
					['jit.vmdef']=true
				}
			},
			['jit.p']={
				mdeps={
					jit=true,
					['jit.profile']=true,
					['jit.vmdef']=true
				}
			},
			['jit.profile']={
			},
			['jit.util']={
			},
			['jit.v']={
				mdeps={
					jit=true,
					['jit.util']=true,
					['jit.vmdef']=true
				}
			},
			['jit.vmdef']={
			},
			['jit.zone']={
			},
			math={
			},
			os={
			},
			package={
			},
			strict={
			},
			string={
			},
			table={
			},
			['table.clone']={
			},
			['table.isarray']={
			},
			['table.isempty']={
			},
			['table.new']={
			},
			['table.nkeys']={
			},
			['thread.exdata']={
			}
		},
		luapower={
			luapower={
				mdeps={
					ffi=true,
					glue=true,
					lfs=true,
					luapower_rpc=true
				}
			},
			luapower_cli={
			},
			luapower_rpc={
				mdeps={
					glue=true,
					luastate=true,
					pp=true
				}
			}
		},
		['luapower-ci']={
		},
		['luapower-repos']={
		},
		['luapower-repos-dev']={
		},
		luapower_db={
			luapower_db={
			}
		},
		luasec={
			['socket.https']={
				mdeps={
					ltn12=true,
					socket=true,
					['socket.http']=true,
					['socket.url']=true,
					ssl=true
				}
			},
			ssl={
				mdeps={
					['ssl.config']=true,
					['ssl.context']=true,
					['ssl.core']=true,
					['ssl.x509']=true
				}
			}
		},
		luastate={
			lua_h={
				mdeps={
					ffi=true
				}
			},
			luajit_h={
				mdeps={
					ffi=true,
					lua_h=true
				}
			},
			luastate={
				mdeps={
					ffi=true,
					luajit_h=true
				}
			}
		},
		lx={
			lx={
				ffi_deps={
					lx=true
				},
				mdeps={
					ffi=true
				}
			}
		},
		lz4={
			lz4={
				ffi_deps={
					lz4=true
				},
				mdeps={
					ffi=true
				}
			}
		},
		md5={
			md5={
				ffi_deps={
					md5=true
				},
				mdeps={
					ffi=true
				}
			}
		},
		['mingw64-headers']={
		},
		minizip={
			minizip={
				ffi_deps={
					minizip=true
				},
				mdeps={
					bit=true,
					ffi=true,
					glue=true,
					minizip_h=true
				}
			},
			minizip_h={
				mdeps={
					ffi=true
				}
			}
		},
		mustache={
			mustache={
			}
		},
		mysql={
			mysql={
				mdeps={
					bit=true,
					ffi=true,
					mysql_h=true
				}
			},
			mysql_h={
				mdeps={
					ffi=true
				}
			},
			mysql_print={
			}
		},
		nginx={
		},
		nw={
			nw={
				mdeps={
					box2d=true,
					events=true,
					ffi=true,
					glue=true,
					nw_winapi=true,
					time=true
				}
			},
			nw_cocoa={
				loaderr='platform not OSX'
			},
			nw_winapi={
				mdeps={
					bit=true,
					bitmap=true,
					box2d=true,
					ffi=true,
					glue=true,
					time=true,
					winapi=true,
					['winapi.bitmap']=true,
					['winapi.clipboard']=true,
					['winapi.cursor']=true,
					['winapi.ddev']=true,
					['winapi.devcaps']=true,
					['winapi.dibitmap']=true,
					['winapi.dpiaware']=true,
					['winapi.dragdrop']=true,
					['winapi.filedialogs']=true,
					['winapi.gdi']=true,
					['winapi.icon']=true,
					['winapi.keyboard']=true,
					['winapi.module']=true,
					['winapi.monitor']=true,
					['winapi.mouse']=true,
					['winapi.notifyiconclass']=true,
					['winapi.panelclass']=true,
					['winapi.rawinput']=true,
					['winapi.shellapi']=true,
					['winapi.spi']=true,
					['winapi.sync']=true,
					['winapi.sysinfo']=true,
					['winapi.systemmetrics']=true,
					['winapi.tooltipclass']=true,
					['winapi.windowclass']=true
				}
			},
			nw_xlib={
				loaderr='platform not Linux'
			}
		},
		objc={
		},
		oo={
			oo={
			}
		},
		opengl={
			gl11={
				mdeps={
					ffi=true,
					gl_types=true
				}
			},
			gl_consts11={
			},
			gl_consts21={
			},
			gl_funcs11={
				mdeps={
					ffi=true,
					gl_types=true
				}
			},
			gl_funcs21={
				mdeps={
					ffi=true,
					gl_types=true
				}
			},
			gl_types={
				mdeps={
					ffi=true
				}
			},
			glu={
				ffi_deps={
					glu32=true
				},
				mdeps={
					ffi=true,
					glu_h=true
				}
			},
			glu_h={
				mdeps={
					ffi=true,
					gl_types=true
				}
			},
			glu_lua={
				mdeps={
					ffi=true,
					['winapi.gl21']=true
				}
			}
		},
		openssl={
		},
		path={
			path={
			}
		},
		path2d={
			path2d={
				mdeps={
					glue=true,
					path2d_arc=true,
					path2d_arc_3p=true,
					path2d_bezier2=true,
					path2d_bezier2_hit=true,
					path2d_bezier3=true,
					path2d_bezier3_hit=true,
					path2d_circle_3p=true,
					path2d_line=true,
					path2d_point=true,
					path2d_shapes=true,
					path2d_svgarc=true,
					path2d_text=true,
					pp=true
				}
			},
			path2d_arc={
				mdeps={
					path2d_bezier3=true,
					path2d_line=true,
					path2d_point=true
				}
			},
			path2d_arc_3p={
				mdeps={
					path2d_arc=true,
					path2d_circle_3p=true,
					path2d_point=true
				}
			},
			path2d_bezier2={
				autoloads={
					hit='path2d_bezier2_hit',
					interpolate='path2d_bezier2_ai'
				},
				mdeps={
					glue=true,
					path2d_bezier_length=true,
					path2d_point=true
				}
			},
			path2d_bezier2_ai={
				mdeps={
					path2d_bezier2=true
				}
			},
			path2d_bezier2_hit={
				mdeps={
					eq=true,
					path2d_bezier2=true,
					path2d_point=true
				}
			},
			path2d_bezier3={
				autoloads={
					hit='path2d_bezier3_hit',
					interpolate='path2d_bezier3_ai'
				},
				mdeps={
					glue=true,
					path2d_bezier_length=true
				}
			},
			path2d_bezier3_ai={
				mdeps={
					path2d_bezier3=true,
					path2d_point=true
				}
			},
			path2d_bezier3_hit={
				mdeps={
					path2d_bezier3=true,
					path2d_point=true
				}
			},
			path2d_bezier_length={
				mdeps={
					path2d_point=true
				}
			},
			path2d_cairo={
				mdeps={
					path2d=true,
					path2d_bezier2=true
				}
			},
			path2d_catmullrom={
			},
			path2d_circle_3p={
				mdeps={
					path2d_point=true
				}
			},
			path2d_editor={
				mdeps={
					glue=true,
					path2d=true,
					path2d_arc=true,
					path2d_arc_3p=true,
					path2d_circle_3p=true,
					path2d_line=true,
					path2d_point=true,
					path2d_shapes=true,
					path2d_svgarc=true
				}
			},
			path2d_line={
				mdeps={
					path2d_point=true
				}
			},
			path2d_point={
			},
			path2d_polyline={
				mdeps={
					path2d_line=true
				}
			},
			path2d_shapes={
				mdeps={
					path2d_circle_3p=true,
					path2d_point=true
				}
			},
			path2d_svgarc={
				mdeps={
					path2d_arc=true,
					path2d_line=true
				}
			},
			path2d_text={
			}
		},
		pcre={
		},
		pcre2={
		},
		pixman={
		},
		pp={
			pp={
			}
		},
		proc={
			proc={
				mdeps={
					bit=true,
					ffi=true,
					glue=true,
					winapi=true,
					['winapi.process']=true
				}
			}
		},
		pthread={
			pthread={
				ffi_deps={
					['libwinpthread-1']=true
				},
				mdeps={
					ffi=true
				}
			}
		},
		rangelist={
			rangelist={
				mdeps={
					glue=true
				}
			}
		},
		resolver={
			resolver={
				mdeps={
					bit=true,
					['table.new']=true
				}
			}
		},
		rs232={
			rs232={
				mdeps={
					ffi=true,
					fs=true
				}
			}
		},
		rsync={
			rsync={
				mdeps={
					bit=true,
					ffi=true
				}
			}
		},
		sha1={
			sha1={
			}
		},
		sha2={
			sha2={
				ffi_deps={
					sha2=true
				},
				mdeps={
					ffi=true
				}
			}
		},
		shm={
			shm={
				loaderr='platform not Linux'
			}
		},
		socket={
			ltn12={
			},
			mime={
				mdeps={
					ltn12=true,
					['mime.core']=true
				}
			},
			['mime.core']={
			},
			socket={
				mdeps={
					['socket.core']=true
				}
			},
			['socket.core']={
			},
			['socket.ftp']={
				mdeps={
					ltn12=true,
					socket=true,
					['socket.tp']=true,
					['socket.url']=true
				}
			},
			['socket.headers']={
				mdeps={
					socket=true
				}
			},
			['socket.http']={
				mdeps={
					ltn12=true,
					mime=true,
					socket=true,
					['socket.headers']=true,
					['socket.url']=true
				}
			},
			['socket.mbox']={
			},
			['socket.smtp']={
				mdeps={
					ltn12=true,
					mime=true,
					socket=true,
					['socket.headers']=true,
					['socket.tp']=true
				}
			},
			['socket.tftp']={
				mdeps={
					ltn12=true,
					socket=true,
					['socket.url']=true
				}
			},
			['socket.tp']={
				mdeps={
					ltn12=true,
					socket=true
				}
			},
			['socket.url']={
				mdeps={
					socket=true
				}
			}
		},
		socketloop={
			socketloop={
				autoloads={
				},
				mdeps={
					glue=true,
					socket=true
				}
			}
		},
		struct={
			struct={
			}
		},
		terra={
			asdl={
			},
			terra={
				mdeps={
					asdl=true,
					terralib=true
				}
			},
			['terra.parsing']={
			},
			['terra.std']={
			},
			terralib={
				loaderr='.\\terralib.lua:1: terra not loaded'
			},
			terralib_luapower={
				loaderr='.\\terralib_luapower.lua:4: terra not loaded'
			}
		},
		['terra-arrayfreelist']={
			['terra.arrayfreelist']={
				autoloads={
					arr='terra/dynarray',
					arrview='terra/arrayview',
					random='terra/random',
					randomseed='terra/random',
					set='terra/hashmap'
				},
				mdeps={
					['terra.low']=true
				}
			}
		},
		['terra-arrayview']={
			['terra.arrayview']={
				autoloads={
					arr='terra/dynarray',
					arrview='terra/arrayview',
					random='terra/random',
					randomseed='terra/random',
					set='terra/hashmap'
				},
				mdeps={
					['terra.low']=true
				}
			},
			['terra.rawstringview']={
				autoloads={
					arrview='terra/arrayview',
					random='terra/random',
					randomseed='terra/random',
					set='terra/hashmap'
				},
				mdeps={
					['terra.dynarray']=true,
					['terra.low']=true
				}
			}
		},
		['terra-binder']={
			['terra.binder']={
				mdeps={
					['terra.low']=true
				}
			}
		},
		['terra-bitarray']={
			['terra.bitarray']={
				mdeps={
					['terra.box2d']=true,
					['terra.low']=true
				}
			}
		},
		['terra-bitmap']={
			['terra.bitmap']={
				mdeps={
					['terra.low']=true
				}
			}
		},
		['terra-box2d']={
			['terra.box2d']={
				autoloads={
					arr='terra/dynarray',
					arrview='terra/arrayview',
					random='terra/random',
					randomseed='terra/random',
					set='terra/hashmap'
				},
				mdeps={
					['terra.low']=true
				}
			}
		},
		['terra-boxblur']={
			boxblurlib_h={
				ffi_deps={
					boxblurlib=true
				},
				mdeps={
					ffi=true
				}
			},
			['terra.boxblur']={
				autoloads={
					arrview='terra/arrayview',
					random='terra/random',
					randomseed='terra/random',
					set='terra/hashmap'
				},
				mdeps={
					['terra.bitmap']=true,
					['terra.low']=true
				}
			}
		},
		['terra-cairo']={
			['terra.cairo']={
				loaderr='.\\terra/low.t:479: attempt to index local \'T\' (a nil value)'
			}
		},
		['terra-dynarray']={
			['terra.dynarray']={
				autoloads={
					arrview='terra/arrayview',
					random='terra/random',
					randomseed='terra/random',
					set='terra/hashmap'
				},
				mdeps={
					['terra.arrayview']=true,
					['terra.low']=true
				}
			}
		},
		['terra-fixedfreelist']={
			['terra.fixedfreelist']={
				autoloads={
					arr='terra/dynarray',
					arrview='terra/arrayview',
					random='terra/random',
					randomseed='terra/random',
					set='terra/hashmap'
				},
				mdeps={
					['terra.low']=true
				}
			}
		},
		['terra-hashmap']={
			['terra.hashmap']={
				autoloads={
					arrview='terra/arrayview',
					random='terra/random',
					randomseed='terra/random',
					set='terra/hashmap'
				},
				mdeps={
					['terra.low']=true
				}
			}
		},
		['terra-layer']={
			layer={
				mdeps={
					ffi=true,
					glue=true,
					layer_h=true
				}
			},
			layer_h={
				ffi_deps={
					layer=true
				},
				mdeps={
					ffi=true
				}
			},
			['layer_test.layer_test_state']={
			},
			['layer_test.layer_test_state_1']={
			},
			['layer_test.layer_test_state_10']={
			},
			['layer_test.layer_test_state_11']={
			},
			['layer_test.layer_test_state_2']={
			},
			['layer_test.layer_test_state_3']={
			},
			['layer_test.layer_test_state_4']={
			},
			['layer_test.layer_test_state_5']={
			},
			['layer_test.layer_test_state_7']={
			},
			['layer_test.layer_test_state_8']={
			},
			['layer_test.layer_test_state_subsegs']={
			},
			['layer_test.layer_test_state_todo']={
			},
			layer_test_state={
			},
			['terra.layer']={
				loaderr='.\\terra/low.t:73: .\\terra/low.t:479: attempt to index local \'T\' (a nil value)'
			},
			['terra.layer_api']={
				loaderr='.\\terra/layer_api.t:42: .\\terra/low.t:73: .\\terra/low.t:479: attempt to index local \'T\' (a nil value)'
			}
		},
		['terra-linkedlist']={
			['terra.linkedlist']={
				autoloads={
					arrview='terra/arrayview',
					random='terra/random',
					randomseed='terra/random',
					set='terra/hashmap'
				},
				mdeps={
					['terra.low']=true
				}
			}
		},
		['terra-low']={
			['terra.low']={
				autoloads={
					arr='terra/dynarray',
					arrview='terra/arrayview',
					random='terra/random',
					randomseed='terra/random',
					set='terra/hashmap'
				},
				mdeps={
					ffi=true,
					glue=true,
					['jit.zone']=true,
					pp=true
				}
			},
			['terra.memcheck']={
				autoloads={
					arr='terra/dynarray',
					arrview='terra/arrayview',
					random='terra/random',
					randomseed='terra/random',
					set='terra/hashmap'
				},
				mdeps={
					['terra.hashmap']=true,
					['terra.low']=true
				}
			}
		},
		['terra-lrucache']={
			['terra.lrucache']={
				autoloads={
					arrview='terra/arrayview',
					random='terra/random',
					randomseed='terra/random',
					set='terra/hashmap'
				},
				mdeps={
					['terra.linkedlist']=true,
					['terra.low']=true
				}
			}
		},
		['terra-oo']={
			['terra.oo']={
				mdeps={
					['terra.low']=true
				}
			}
		},
		['terra-phf']={
			['terra.phf']={
				autoloads={
					arr='terra/dynarray',
					arrview='terra/arrayview',
					random='terra/random',
					randomseed='terra/random',
					set='terra/hashmap'
				},
				mdeps={
					['terra.low']=true
				}
			}
		},
		['terra-random']={
			['terra.random']={
				loaderr='.\\terralib.lua:4139: variable \'Strict\' is not declared'
			}
		},
		['terra-tr']={
			['terra.tr']={
				loaderr='.\\terra/tr.t:58: glue.lua:741: variable \'color\' is not declared'
			},
			['terra.tr_align']={
				loaderr='.\\terra/tr_align.t:6: glue.lua:741: variable \'color\' is not declared'
			},
			['terra.tr_api']={
				loaderr='.\\terra/tr_api.t:49: .\\terra/low.t:73: .\\terra/low.t:479: attempt to index local \'T\' (a nil value)'
			},
			['terra.tr_clip']={
				loaderr='glue.lua:741: variable \'color\' is not declared'
			},
			['terra.tr_cursor']={
				loaderr='.\\terra/tr_cursor.t:42: glue.lua:741: variable \'color\' is not declared'
			},
			['terra.tr_font']={
				loaderr='.\\terra/tr_font.t:12: glue.lua:741: variable \'color\' is not declared'
			},
			['terra.tr_itemize']={
				loaderr='.\\terra/tr_itemize.t:15: glue.lua:741: variable \'color\' is not declared'
			},
			['terra.tr_itemize_detect_lang']={
				loaderr='.\\terra/tr_itemize_detect_lang.t:6: glue.lua:741: variable \'color\' is not declared'
			},
			['terra.tr_itemize_detect_script']={
				loaderr='.\\terra/tr_itemize_detect_script.t:5: glue.lua:741: variable \'color\' is not declared'
			},
			['terra.tr_layoutedit']={
				loaderr='.\\terra/tr_layoutedit.t:6: glue.lua:741: variable \'color\' is not declared'
			},
			['terra.tr_paint']={
				loaderr='.\\terra/tr_paint.t:6: glue.lua:741: variable \'color\' is not declared'
			},
			['terra.tr_paint_cairo']={
				loaderr='.\\terra/low.t:73: .\\terra/low.t:479: attempt to index local \'T\' (a nil value)'
			},
			['terra.tr_rasterize']={
				loaderr='.\\terra/tr_rasterize.t:10: glue.lua:741: variable \'color\' is not declared'
			},
			['terra.tr_rle']={
				mdeps={
					['terra.low']=true
				}
			},
			['terra.tr_selection']={
				loaderr='.\\terra/tr_selection.t:6: glue.lua:741: variable \'color\' is not declared'
			},
			['terra.tr_shape']={
				loaderr='.\\terra/tr_shape.t:13: glue.lua:741: variable \'color\' is not declared'
			},
			['terra.tr_shape_detect_lang']={
				loaderr='.\\terra/tr_shape_detect_lang.t:6: glue.lua:741: variable \'color\' is not declared'
			},
			['terra.tr_shape_detect_script']={
				loaderr='.\\terra/tr_shape_detect_script.t:5: glue.lua:741: variable \'color\' is not declared'
			},
			['terra.tr_shape_word']={
				loaderr='.\\terra/tr_shape_word.t:6: glue.lua:741: variable \'color\' is not declared'
			},
			['terra.tr_spanedit']={
				loaderr='.\\terra/tr_spanedit.t:7: glue.lua:741: variable \'color\' is not declared'
			},
			['terra.tr_types']={
				loaderr='glue.lua:741: variable \'color\' is not declared'
			},
			['terra.tr_underline']={
				loaderr='.\\terra/tr_underline.t:6: glue.lua:741: variable \'color\' is not declared'
			},
			['terra.tr_wrap']={
				loaderr='.\\terra/tr_wrap.t:6: glue.lua:741: variable \'color\' is not declared'
			},
			['terra.tr_wrap_reorder']={
				loaderr='.\\terra/tr_wrap_reorder.t:14: glue.lua:741: variable \'color\' is not declared'
			},
			['terra.tr_wrap_smawk']={
				loaderr='.\\terralib.lua:4115: error loading terra module terra.tr_wrap_smawk from file .\\terra/tr_wrap_smawk.t'
			}
		},
		['terra-utf8']={
			['terra.utf8']={
				loaderr='.\\terra/utf8.t:133: failed attempting to index field \'utf8\' in name \'utf8.decode.count\' (expected a table but found table)'
			}
		},
		['terra.arrayfreelist']={
			['terra.arrayfreelist']={
				mdeps={
					['terra.low']=true
				}
			}
		},
		['terra.arrayview']={
			['terra.arrayview']={
				mdeps={
					['terra.low']=true
				}
			},
			['terra.rawstringview']={
				mdeps={
					['terra.arrayview']=true,
					['terra.dynarray']=true,
					['terra.low']=true
				}
			}
		},
		['terra.binder']={
			['terra.binder']={
				loaderr='.\\terra\\binder.lua:70: terra not loaded'
			}
		},
		['terra.bitarray']={
			['terra.bitarray']={
				loaderr='.\\terra/bitarray.t:14: attempt to call global \'rect\' (a nil value)'
			}
		},
		['terra.bitmap']={
			['terra.bitmap']={
				mdeps={
					['terra.low']=true
				}
			}
		},
		['terra.box2d']={
			['terra.box2d']={
				mdeps={
					['terra.low']=true
				}
			}
		},
		['terra.boxblur']={
			boxblurlib_h={
				loaderr='.\\boxblurlib_h.lua:2: cannot load module \'boxblurlib\': The specified module could not be found.'
			},
			['terra.boxblur']={
				mdeps={
					['terra.bitmap']=true,
					['terra.low']=true
				}
			}
		},
		['terra.cairo']={
			['terra.cairo']={
				mdeps={
					cairo_h=true,
					['terra.bitmap']=true,
					['terra.low']=true
				}
			}
		},
		['terra.dynarray']={
			['terra.dynarray']={
				mdeps={
					['terra.arrayview']=true,
					['terra.low']=true
				}
			}
		},
		['terra.fixedfreelist']={
			['terra.fixedfreelist']={
				mdeps={
					['terra.low']=true
				}
			}
		},
		['terra.hashmap']={
			['terra.hashmap']={
				mdeps={
					['terra.low']=true
				}
			}
		},
		['terra.layer']={
			layer={
				mdeps={
					ffi=true,
					glue=true,
					layer_h=true
				}
			},
			layer_h={
				ffi_deps={
					layer=true
				},
				mdeps={
					ffi=true
				}
			},
			['layer_test.layer_test_state']={
			},
			['layer_test.layer_test_state_1']={
			},
			['layer_test.layer_test_state_10']={
			},
			['layer_test.layer_test_state_11']={
			},
			['layer_test.layer_test_state_2']={
			},
			['layer_test.layer_test_state_3']={
			},
			['layer_test.layer_test_state_4']={
			},
			['layer_test.layer_test_state_5']={
			},
			['layer_test.layer_test_state_7']={
			},
			['layer_test.layer_test_state_8']={
			},
			['layer_test.layer_test_state_subsegs']={
			},
			['layer_test.layer_test_state_todo']={
			},
			layer_test_state={
			},
			['terra.layer']={
				loaderr='.\\terra/low.t:73: .\\terra/low.t:73: .\\terra/tr_types.t:106: attempt to call global \'rect\' (a nil value)'
			},
			['terra.layer_api']={
				loaderr='.\\terra/layer_api.t:42: .\\terra/low.t:73: .\\terra/low.t:73: .\\terra/tr_types.t:106: attempt to call global \'rect\' (a nil value)'
			}
		},
		['terra.linkedlist']={
			['terra.linkedlist']={
				mdeps={
					['terra.low']=true
				}
			}
		},
		['terra.low']={
			['terra.low']={
				autoloads={
					arr='terra.dynarray',
					arrview='terra.arrayview',
					map='terra.hashmap',
					random='terra.random',
					randomseed='terra.random',
					set='terra.hashmap'
				},
				mdeps={
					ffi=true,
					glue=true,
					['jit.zone']=true,
					pp=true
				}
			},
			['terra.memcheck']={
				autoloads={
					arr='terra.dynarray',
					arrview='terra.arrayview',
					random='terra.random',
					randomseed='terra.random',
					set='terra.hashmap'
				},
				mdeps={
					['terra.hashmap']=true,
					['terra.low']=true
				}
			}
		},
		['terra.lrucache']={
			['terra.lrucache']={
				mdeps={
					['terra.linkedlist']=true,
					['terra.low']=true
				}
			}
		},
		['terra.oo']={
			['terra.oo']={
				mdeps={
					['terra.low']=true
				}
			}
		},
		['terra.phf']={
			['terra.phf']={
				mdeps={
					['terra.low']=true
				}
			}
		},
		['terra.random']={
			['terra.random']={
				mdeps={
					['terra.low']=true
				}
			}
		},
		['terra.tr']={
			['terra.tr']={
				loaderr='.\\terra/tr.t:58: .\\terra/tr_types.t:13: terra.tr_paint_cairo not loaded'
			},
			['terra.tr_align']={
				loaderr='.\\terra/tr_align.t:6: .\\terra/tr_types.t:13: terra.tr_paint_cairo not loaded'
			},
			['terra.tr_api']={
				loaderr='.\\terra/tr_api.t:49: .\\terra/low.t:73: .\\terra/tr_types.t:106: attempt to call global \'rect\' (a nil value)'
			},
			['terra.tr_clip']={
				loaderr='.\\terra/tr_clip.t:10: .\\terra/tr_types.t:13: terra.tr_paint_cairo not loaded'
			},
			['terra.tr_cursor']={
				loaderr='.\\terra/tr_cursor.t:42: .\\terra/tr_types.t:13: terra.tr_paint_cairo not loaded'
			},
			['terra.tr_font']={
				loaderr='.\\terra/tr_font.t:12: .\\terra/tr_types.t:13: terra.tr_paint_cairo not loaded'
			},
			['terra.tr_itemize']={
				loaderr='.\\terra/tr_itemize.t:15: .\\terra/tr_types.t:13: terra.tr_paint_cairo not loaded'
			},
			['terra.tr_itemize_detect_lang']={
				loaderr='.\\terra/tr_itemize_detect_lang.t:6: .\\terra/tr_types.t:13: terra.tr_paint_cairo not loaded'
			},
			['terra.tr_itemize_detect_script']={
				loaderr='.\\terra/tr_itemize_detect_script.t:5: .\\terra/tr_types.t:13: terra.tr_paint_cairo not loaded'
			},
			['terra.tr_layoutedit']={
				loaderr='.\\terra/tr_layoutedit.t:6: .\\terra/tr_types.t:13: terra.tr_paint_cairo not loaded'
			},
			['terra.tr_paint']={
				loaderr='.\\terra/tr_paint.t:6: .\\terra/tr_types.t:13: terra.tr_paint_cairo not loaded'
			},
			['terra.tr_paint_cairo']={
				loaderr='.\\terra/low.t:73: .\\terra/tr_types.t:106: attempt to call global \'rect\' (a nil value)'
			},
			['terra.tr_rasterize']={
				loaderr='.\\terra/tr_rasterize.t:10: .\\terra/tr_types.t:13: terra.tr_paint_cairo not loaded'
			},
			['terra.tr_rle']={
				mdeps={
					['terra.low']=true
				}
			},
			['terra.tr_selection']={
				loaderr='.\\terra/tr_selection.t:6: .\\terra/tr_types.t:13: terra.tr_paint_cairo not loaded'
			},
			['terra.tr_shape']={
				loaderr='.\\terra/tr_shape.t:13: .\\terra/tr_types.t:13: terra.tr_paint_cairo not loaded'
			},
			['terra.tr_shape_detect_lang']={
				loaderr='.\\terra/tr_shape_detect_lang.t:6: .\\terra/tr_types.t:13: terra.tr_paint_cairo not loaded'
			},
			['terra.tr_shape_detect_script']={
				loaderr='.\\terra/tr_shape_detect_script.t:5: .\\terra/tr_types.t:13: terra.tr_paint_cairo not loaded'
			},
			['terra.tr_shape_word']={
				loaderr='.\\terra/tr_shape_word.t:6: .\\terra/tr_types.t:13: terra.tr_paint_cairo not loaded'
			},
			['terra.tr_spanedit']={
				loaderr='.\\terra/tr_spanedit.t:7: .\\terra/tr_types.t:13: terra.tr_paint_cairo not loaded'
			},
			['terra.tr_types']={
				loaderr='.\\terra/tr_types.t:13: terra.tr_paint_cairo not loaded'
			},
			['terra.tr_underline']={
				loaderr='.\\terra/tr_underline.t:6: .\\terra/tr_types.t:13: terra.tr_paint_cairo not loaded'
			},
			['terra.tr_wrap']={
				loaderr='.\\terra/tr_wrap.t:6: .\\terra/tr_types.t:13: terra.tr_paint_cairo not loaded'
			},
			['terra.tr_wrap_reorder']={
				loaderr='.\\terra/tr_wrap_reorder.t:14: .\\terra/tr_types.t:13: terra.tr_paint_cairo not loaded'
			},
			['terra.tr_wrap_smawk']={
			}
		},
		['terra.utf8']={
			['terra.utf8']={
				mdeps={
					['terra.arrayview']=true,
					['terra.dynarray']=true,
					['terra.low']=true
				}
			}
		},
		testui={
			testui={
				mdeps={
					color=true,
					ffi=true,
					glue=true,
					nw=true
				}
			}
		},
		thread={
			thread={
				mdeps={
					ffi=true,
					glue=true,
					luastate=true,
					pthread=true
				}
			}
		},
		time={
			time={
				mdeps={
					ffi=true
				}
			}
		},
		tr={
			tr={
				mdeps={
					bit=true,
					box2d=true,
					ffi=true,
					freetype=true,
					fribidi=true,
					glue=true,
					harfbuzz=true,
					libunibreak=true,
					lrucache=true,
					tr_shape_lang=true,
					tr_shape_reorder=true,
					tr_shape_script=true,
					utf8=true
				}
			},
			tr_raster_cairo={
				mdeps={
					box2d=true,
					cairo=true,
					color=true,
					ffi=true,
					freetype=true,
					glue=true,
					['jit.zone']=true,
					tr_raster_ft=true
				}
			},
			tr_raster_ft={
				mdeps={
					bit=true,
					ffi=true,
					font_db=true,
					freetype=true,
					glue=true,
					['jit.zone']=true,
					lrucache=true
				}
			},
			tr_shape_lang={
				mdeps={
					ffi=true,
					harfbuzz=true
				}
			},
			tr_shape_reorder={
				mdeps={
					bit=true,
					glue=true
				}
			},
			tr_shape_script={
				mdeps={
					bit=true,
					glue=true,
					harfbuzz=true
				}
			}
		},
		tr0={
			tr0={
				mdeps={
					bit=true,
					box2d=true,
					ffi=true,
					freetype=true,
					fribidi=true,
					glue=true,
					harfbuzz=true,
					libunibreak=true,
					lrucache=true,
					tr0_shape_lang=true,
					tr0_shape_reorder=true,
					tr0_shape_script=true,
					utf8=true
				}
			},
			tr0_raster_cairo={
				mdeps={
					box2d=true,
					cairo=true,
					color=true,
					ffi=true,
					freetype=true,
					glue=true,
					['jit.zone']=true,
					tr0_raster_ft=true
				}
			},
			tr0_raster_ft={
				mdeps={
					bit=true,
					ffi=true,
					font_db=true,
					freetype=true,
					glue=true,
					['jit.zone']=true,
					lrucache=true
				}
			},
			tr0_shape_lang={
				mdeps={
					ffi=true,
					harfbuzz=true
				}
			},
			tr0_shape_reorder={
				mdeps={
					bit=true,
					glue=true
				}
			},
			tr0_shape_script={
				mdeps={
					bit=true,
					glue=true,
					harfbuzz=true
				}
			}
		},
		tuple={
			tuple={
			}
		},
		tweening={
			tweening={
			}
		},
		ucdn={
			ucdn={
				ffi_deps={
					ucdn=true
				},
				mdeps={
					ffi=true
				}
			}
		},
		ui={
			ui={
				mdeps={
					box2d=true,
					boxblur=true,
					cairo=true,
					color=true,
					easing=true,
					events=true,
					ffi=true,
					glue=true,
					['jit.zone']=true,
					nw=true,
					oo=true,
					time=true,
					tr0=true
				}
			},
			ui_button={
				mdeps={
					glue=true,
					ui=true
				}
			},
			ui_calendar={
				mdeps={
					glue=true,
					tr0_raster_cairo=true,
					ui=true,
					ui_grid=true
				}
			},
			ui_colorpicker={
				mdeps={
					bitmap=true,
					cairo=true,
					color=true,
					glue=true,
					ui=true,
					ui_button=true,
					ui_editbox=true
				}
			},
			ui_dropdown={
				mdeps={
					glue=true,
					time=true,
					ui=true,
					ui_editbox=true,
					ui_popup=true,
					ui_scrollbox=true
				}
			},
			ui_editbox={
				mdeps={
					box2d=true,
					glue=true,
					tr0=true,
					ui=true
				}
			},
			ui_grid={
				mdeps={
					box2d=true,
					glue=true,
					ui=true,
					ui_editbox=true,
					ui_scrollbox=true
				}
			},
			ui_layout_editor={
				mdeps={
					box2d=true,
					ui=true
				}
			},
			ui_list={
				mdeps={
					glue=true,
					ui=true
				}
			},
			ui_menu={
				mdeps={
					ui=true
				}
			},
			ui_popup={
				mdeps={
					glue=true,
					ui=true
				}
			},
			ui_progressbar={
				mdeps={
					ui=true
				}
			},
			ui_scrollbox={
				mdeps={
					box2d=true,
					glue=true,
					ui=true
				}
			},
			ui_slider={
				mdeps={
					glue=true,
					ui=true
				}
			},
			ui_tablist={
				mdeps={
					box2d=true,
					glue=true,
					ui=true,
					ui_button=true
				}
			},
			ui_zoomcalendar={
				mdeps={
					glue=true,
					ui=true
				}
			}
		},
		unit={
			unit={
				mdeps={
					glue=true,
					pp=true
				}
			}
		},
		unixperms={
			unixperms={
				mdeps={
					bit=true
				}
			}
		},
		utf8={
			utf8={
				mdeps={
					bit=true,
					ffi=true
				}
			}
		},
		utf8quot={
			utf8quot={
			}
		},
		videoinput={
			videoinput={
				mdeps={
					ffi=true,
					glue=true,
					videoinput_dshow=true
				}
			},
			videoinput_cocoa={
				loaderr='platform not OSX'
			},
			videoinput_dshow={
			}
		},
		webb={
			action={
				loaderr='.\\action.lua:60: attempt to call global \'config\' (a nil value)'
			},
			auth={
				loaderr='.\\auth.lua:118: module \'resty.random\' not found'
			},
			lp={
			},
			ngx={
				loaderr='.\\ngx.lua:13: attempt to index global \'ngx\' (a nil value)'
			},
			query={
				loaderr='.\\query.lua:29: module \'resty.mysql\' not found'
			},
			['resty.socket']={
				mdeps={
					socket=true
				}
			},
			sendmail={
				mdeps={
					ltn12=true,
					mime=true,
					['resty.socket']=true,
					['socket.smtp']=true
				}
			},
			session={
				loaderr='.\\session.lua:1: attempt to index global \'ngx\' (a nil value)'
			},
			webb={
				loaderr='.\\webb.lua:430: attempt to index global \'ngx\' (a nil value)'
			},
			webbjs={
				loaderr='.\\webbjs.lua:61: .\\webb.lua:430: attempt to index global \'ngx\' (a nil value)'
			}
		},
		winapi={
			winapi={
				mdeps={
					['winapi.init']=true
				}
			},
			['winapi.accelerator']={
				mdeps={
					winapi=true,
					['winapi.winuser']=true
				}
			},
			['winapi.basebuttonclass']={
				mdeps={
					winapi=true,
					['winapi.button']=true,
					['winapi.controlclass']=true,
					['winapi.imagelistclass']=true
				}
			},
			['winapi.basewindowclass']={
				mdeps={
					winapi=true,
					['winapi.dpiaware']=true,
					['winapi.gdi']=true,
					['winapi.handlelist']=true,
					['winapi.keyboard']=true,
					['winapi.monitor']=true,
					['winapi.mouse']=true,
					['winapi.vobject']=true,
					['winapi.window']=true
				}
			},
			['winapi.bitmap']={
				mdeps={
					winapi=true
				}
			},
			['winapi.bitmappanel']={
				mdeps={
					bit=true,
					ffi=true,
					winapi=true,
					['winapi.bitmap']=true,
					['winapi.dibitmap']=true,
					['winapi.panelclass']=true
				}
			},
			['winapi.bitmask']={
				mdeps={
					['winapi.namespace']=true,
					['winapi.util']=true
				}
			},
			['winapi.button']={
				mdeps={
					winapi=true,
					['winapi.comctl']=true,
					['winapi.window']=true
				}
			},
			['winapi.buttonclass']={
				mdeps={
					winapi=true,
					['winapi.basebuttonclass']=true
				}
			},
			['winapi.checkboxclass']={
				mdeps={
					winapi=true,
					['winapi.basebuttonclass']=true
				}
			},
			['winapi.class']={
				mdeps={
					winapi=true
				}
			},
			['winapi.clipboard']={
				mdeps={
					winapi=true,
					['winapi.memory']=true
				}
			},
			['winapi.color']={
				mdeps={
					winapi=true,
					['winapi.winuser']=true
				}
			},
			['winapi.colorchooser']={
				mdeps={
					winapi=true,
					['winapi.comdlg']=true
				}
			},
			['winapi.combobox']={
				mdeps={
					winapi=true,
					['winapi.window']=true
				}
			},
			['winapi.comboboxclass']={
				mdeps={
					winapi=true,
					['winapi.comboboxex']=true,
					['winapi.controlclass']=true
				}
			},
			['winapi.comboboxex']={
				mdeps={
					winapi=true,
					['winapi.combobox']=true,
					['winapi.comctl']=true,
					['winapi.itemlist']=true
				}
			},
			['winapi.comctl']={
				ffi_deps={
					comctl32=true
				},
				mdeps={
					winapi=true,
					['winapi.winuser']=true
				}
			},
			['winapi.comdlg']={
				ffi_deps={
					comdlg32=true
				},
				mdeps={
					winapi=true,
					['winapi.winuser']=true
				}
			},
			['winapi.controlclass']={
				mdeps={
					winapi=true,
					['winapi.basewindowclass']=true,
					['winapi.comctl']=true
				}
			},
			['winapi.cursor']={
				mdeps={
					winapi=true,
					['winapi.winuser']=true
				}
			},
			['winapi.ddev']={
				mdeps={
					winapi=true
				}
			},
			['winapi.debug']={
				mdeps={
					['winapi.namespace']=true
				}
			},
			['winapi.devcaps']={
				mdeps={
					winapi=true
				}
			},
			['winapi.dibitmap']={
				mdeps={
					winapi=true
				}
			},
			['winapi.dpiaware']={
				mdeps={
					winapi=true,
					['winapi.monitor']=true
				}
			},
			['winapi.dragdrop']={
				mdeps={
					winapi=true,
					['winapi.idataobject']=true,
					['winapi.ole']=true
				}
			},
			['winapi.dsound']={
				ffi_deps={
					dsound=true
				},
				mdeps={
					winapi=true,
					['winapi.ole']=true
				}
			},
			['winapi.edit']={
				mdeps={
					winapi=true,
					['winapi.comctl']=true,
					['winapi.window']=true
				}
			},
			['winapi.editclass']={
				mdeps={
					winapi=true,
					['winapi.controlclass']=true,
					['winapi.edit']=true,
					['winapi.gdi']=true
				}
			},
			['winapi.filedialogs']={
				mdeps={
					winapi=true,
					['winapi.comdlg']=true
				}
			},
			['winapi.filemapping']={
				mdeps={
					winapi=true,
					['winapi.winbase']=true,
					['winapi.winnt']=true
				}
			},
			['winapi.font']={
				mdeps={
					winapi=true,
					['winapi.gdi']=true,
					['winapi.logfonttype']=true,
					['winapi.winuser']=true
				}
			},
			['winapi.fontex']={
				mdeps={
					winapi=true,
					['winapi.font']=true
				}
			},
			['winapi.gdi']={
				mdeps={
					winapi=true,
					['winapi.winuser']=true
				}
			},
			['winapi.groupboxclass']={
				mdeps={
					winapi=true,
					['winapi.basebuttonclass']=true
				}
			},
			['winapi.handlelist']={
				mdeps={
					winapi=true,
					['winapi.vobject']=true
				}
			},
			['winapi.headercontrol']={
				mdeps={
					winapi=true,
					['winapi.winuser']=true
				}
			},
			['winapi.icon']={
				mdeps={
					winapi=true,
					['winapi.winuser']=true
				}
			},
			['winapi.idataobject']={
				mdeps={
					winapi=true,
					['winapi.ienumformatetc']=true,
					['winapi.ole']=true
				}
			},
			['winapi.ienumformatetc']={
				mdeps={
					winapi=true,
					['winapi.ole']=true
				}
			},
			['winapi.imagelist']={
				mdeps={
					winapi=true,
					['winapi.comctl']=true
				}
			},
			['winapi.imagelistclass']={
				mdeps={
					winapi=true,
					['winapi.handlelist']=true,
					['winapi.imagelist']=true,
					['winapi.itemlist']=true
				}
			},
			['winapi.init']={
				mdeps={
					['winapi.bitmask']=true,
					['winapi.namespace']=true,
					['winapi.struct']=true,
					['winapi.types']=true,
					['winapi.util']=true,
					['winapi.wcs']=true
				}
			},
			['winapi.itemlist']={
				mdeps={
					winapi=true,
					['winapi.vobject']=true
				}
			},
			['winapi.keyboard']={
				mdeps={
					winapi=true
				}
			},
			['winapi.labelclass']={
				mdeps={
					winapi=true,
					['winapi.controlclass']=true,
					['winapi.static']=true
				}
			},
			['winapi.listbox']={
				mdeps={
					winapi=true,
					['winapi.comctl']=true,
					['winapi.window']=true
				}
			},
			['winapi.listboxclass']={
				mdeps={
					winapi=true,
					['winapi.controlclass']=true,
					['winapi.itemlist']=true,
					['winapi.listbox']=true
				}
			},
			['winapi.listview']={
				mdeps={
					winapi=true,
					['winapi.comctl']=true,
					['winapi.window']=true
				}
			},
			['winapi.listviewclass']={
				mdeps={
					winapi=true,
					['winapi.controlclass']=true,
					['winapi.headercontrol']=true,
					['winapi.itemlist']=true,
					['winapi.listview']=true
				}
			},
			['winapi.logfonttype']={
				mdeps={
					ffi=true,
					['winapi.namespace']=true,
					['winapi.types']=true
				}
			},
			['winapi.memory']={
				mdeps={
					winapi=true,
					['winapi.winnt']=true
				}
			},
			['winapi.menu']={
				mdeps={
					winapi=true,
					['winapi.winuser']=true
				}
			},
			['winapi.menuclass']={
				mdeps={
					winapi=true,
					['winapi.handlelist']=true,
					['winapi.itemlist']=true,
					['winapi.menu']=true,
					['winapi.vobject']=true
				}
			},
			['winapi.messagebox']={
				mdeps={
					winapi=true,
					['winapi.comctl']=true,
					['winapi.winuser']=true
				}
			},
			['winapi.mmdevice']={
				mdeps={
					winapi=true,
					['winapi.ole']=true,
					['winapi.propsys']=true,
					['winapi.sstorage']=true,
					['winapi.uuid']=true
				}
			},
			['winapi.mmdeviceclass']={
				mdeps={
					winapi=true,
					['winapi.mmdevice']=true
				}
			},
			['winapi.mmsystem']={
				ffi_deps={
					winmm=true
				},
				mdeps={
					winapi=true,
					['winapi.winuser']=true
				}
			},
			['winapi.module']={
				mdeps={
					winapi=true,
					['winapi.winuser']=true
				}
			},
			['winapi.monitor']={
				mdeps={
					winapi=true,
					['winapi.winuser']=true
				}
			},
			['winapi.mouse']={
				mdeps={
					winapi=true
				}
			},
			['winapi.namespace']={
			},
			['winapi.notifyiconclass']={
				mdeps={
					winapi=true,
					['winapi.handlelist']=true,
					['winapi.shellapi']=true,
					['winapi.vobject']=true,
					['winapi.window']=true
				}
			},
			['winapi.ole']={
				ffi_deps={
					ole32=true
				},
				mdeps={
					winapi=true
				}
			},
			['winapi.panelclass']={
				mdeps={
					winapi=true,
					['winapi.color']=true,
					['winapi.controlclass']=true,
					['winapi.cursor']=true,
					['winapi.winbase']=true
				}
			},
			['winapi.process']={
				mdeps={
					winapi=true,
					['winapi.winbase']=true
				}
			},
			['winapi.propsys']={
				mdeps={
					winapi=true,
					['winapi.sstorage']=true
				}
			},
			['winapi.radiobuttonclass']={
				mdeps={
					winapi=true,
					['winapi.basebuttonclass']=true
				}
			},
			['winapi.rawinput']={
				mdeps={
					winapi=true
				}
			},
			['winapi.registry']={
				mdeps={
					winapi=true
				}
			},
			['winapi.resource']={
				mdeps={
					winapi=true,
					['winapi.winuser']=true
				}
			},
			['winapi.richedit']={
				mdeps={
					winapi=true
				}
			},
			['winapi.rpc']={
				ffi_deps={
					Rpcrt4=true
				},
				mdeps={
					winapi=true
				}
			},
			['winapi.shellapi']={
				ffi_deps={
					Shell32=true
				},
				mdeps={
					winapi=true,
					['winapi.winnt']=true,
					['winapi.winuser']=true
				}
			},
			['winapi.showcase']={
				mdeps={
					winapi=true,
					['winapi.comctl']=true,
					['winapi.imagelistclass']=true,
					['winapi.shellapi']=true,
					['winapi.windowclass']=true
				}
			},
			['winapi.spi']={
				mdeps={
					winapi=true
				}
			},
			['winapi.sstorage']={
				mdeps={
					winapi=true,
					['winapi.ole']=true,
					['winapi.uuid']=true
				}
			},
			['winapi.static']={
				mdeps={
					winapi=true,
					['winapi.window']=true
				}
			},
			['winapi.struct']={
				mdeps={
					['winapi.namespace']=true,
					['winapi.util']=true
				}
			},
			['winapi.sync']={
				mdeps={
					winapi=true,
					['winapi.winbase']=true
				}
			},
			['winapi.sysinfo']={
				mdeps={
					winapi=true
				}
			},
			['winapi.systemmetrics']={
				mdeps={
					winapi=true
				}
			},
			['winapi.tabcontrol']={
				mdeps={
					winapi=true,
					['winapi.comctl']=true,
					['winapi.window']=true
				}
			},
			['winapi.tabcontrolclass']={
				mdeps={
					winapi=true,
					['winapi.controlclass']=true,
					['winapi.itemlist']=true,
					['winapi.tabcontrol']=true
				}
			},
			['winapi.thread']={
				mdeps={
					ffi=true,
					winapi=true,
					['winapi.winbase']=true
				}
			},
			['winapi.time']={
				mdeps={
					winapi=true
				}
			},
			['winapi.toolbar']={
				mdeps={
					winapi=true,
					['winapi.comctl']=true,
					['winapi.window']=true
				}
			},
			['winapi.toolbarclass']={
				mdeps={
					winapi=true,
					['winapi.controlclass']=true,
					['winapi.itemlist']=true,
					['winapi.toolbar']=true
				}
			},
			['winapi.tooltip']={
				mdeps={
					winapi=true,
					['winapi.comctl']=true,
					['winapi.window']=true
				}
			},
			['winapi.tooltipclass']={
				mdeps={
					winapi=true,
					['winapi.basewindowclass']=true,
					['winapi.controlclass']=true,
					['winapi.tooltip']=true
				}
			},
			['winapi.treeview']={
				mdeps={
					winapi=true,
					['winapi.comctl']=true,
					['winapi.window']=true
				}
			},
			['winapi.types']={
				mdeps={
					ffi=true
				}
			},
			['winapi.util']={
				mdeps={
					bit=true,
					ffi=true,
					glue=true,
					['winapi.namespace']=true,
					['winapi.types']=true
				}
			},
			['winapi.uuid']={
				mdeps={
					winapi=true,
					['winapi.rpc']=true
				}
			},
			['winapi.vobject']={
				mdeps={
					events=true,
					winapi=true
				}
			},
			['winapi.volman']={
				mdeps={
					winapi=true
				}
			},
			['winapi.waitemlistclass']={
				mdeps={
					winapi=true,
					['winapi.accelerator']=true,
					['winapi.itemlist']=true
				}
			},
			['winapi.wcs']={
				mdeps={
					['winapi.namespace']=true,
					['winapi.types']=true,
					['winapi.util']=true
				}
			},
			['winapi.winbase']={
				mdeps={
					winapi=true
				}
			},
			['winapi.window']={
				mdeps={
					winapi=true,
					['winapi.gdi']=true,
					['winapi.windowclasses']=true,
					['winapi.winuser']=true,
					['winapi.wmapp']=true
				}
			},
			['winapi.windowclass']={
				mdeps={
					winapi=true,
					['winapi.basewindowclass']=true,
					['winapi.color']=true,
					['winapi.cursor']=true,
					['winapi.menuclass']=true,
					['winapi.waitemlistclass']=true
				}
			},
			['winapi.windowclasses']={
				mdeps={
					winapi=true,
					['winapi.winuser']=true
				}
			},
			['winapi.winnt']={
				mdeps={
					winapi=true
				}
			},
			['winapi.winuser']={
				mdeps={
					winapi=true
				}
			},
			['winapi.wmapp']={
				loaderr='.\\winapi\\wmapp.lua:10: winapi.window not loaded'
			}
		},
		['winapi.cairopanel']={
			['winapi.cairopanel']={
				mdeps={
					bit=true,
					cairo=true,
					ffi=true,
					winapi=true,
					['winapi.bitmappanel']=true
				}
			}
		},
		['winapi.wglpanel']={
			['winapi.gl']={
				mdeps={
					winapi=true,
					['winapi.wgl']=true
				}
			},
			['winapi.gl11']={
				mdeps={
					gl_consts11=true,
					gl_funcs11=true,
					winapi=true,
					['winapi.gl']=true
				}
			},
			['winapi.gl21']={
				mdeps={
					gl_consts21=true,
					gl_funcs21=true,
					winapi=true,
					['winapi.gl']=true
				}
			},
			['winapi.wgl']={
				ffi_deps={
					opengl32=true
				},
				mdeps={
					winapi=true,
					['winapi.winuser']=true
				}
			},
			['winapi.wglext']={
				mdeps={
					gl_types=true,
					winapi=true,
					['winapi.winuser']=true
				}
			},
			['winapi.wglpanel']={
				mdeps={
					winapi=true,
					['winapi.gl11']=true,
					['winapi.panelclass']=true,
					['winapi.wglext']=true
				}
			}
		},
		xlib={
		},
		xxhash={
			xxhash={
				ffi_deps={
					xxhash=true
				},
				mdeps={
					ffi=true,
					xxhash_h=true
				}
			},
			xxhash_h={
				mdeps={
					ffi=true
				}
			}
		},
		zlib={
			zlib={
				ffi_deps={
					z=true
				},
				mdeps={
					ffi=true,
					zlib_h=true
				}
			},
			zlib_h={
				mdeps={
					ffi=true
				}
			}
		}
	}
}