
require'webb_query'

function qmacro.lang_fk(tbl, col)
	return _('char(2) character set ascii not null, foreign key %s',
		pp.macro.fk(tbl, col or 'lang', 'lang', 'lang'))
end

function lang_create_tables()

	query[[
	$table lang (
		lang        $lang not null primary key,
		en_name     $name not null, $uk(lang, en_name),
		name        $name not null, $uk(lang, name),
		decimal_separator     varchar(4) not null default ',',
		thousands_separator   varchar(4) not null default '.'
	);
	]]

	--https://en.wikipedia.org/wiki/Languages_used_on_the_Internet
	--https://meta.wikimedia.org/wiki/Template:List_of_language_names_ordered_by_code
	query[[
		insert ignore into lang
			(lang, en_name, decimal_separator, thousands_separator, name)
		values
			('en', 'English'    , '.', ',', 'English'),
			('ru', 'Russian'    , ',', '.', 'Русский'),
			('tr', 'Turkish'    , ',', '.', 'Türkçe'),
			('es', 'Spanish'    , ',', '.', 'Español'),
			('fa', 'Persian'    , '٫', '٬', 'فارسی'),
			('fr', 'French'     , ',', '.', 'Français'),
			('de', 'German'     , ',', '.', 'Deutsch'),
			('ja', 'Japanese'   , '.', ',', '日本語'),
			('vi', 'Vietnamese' , ',', '.', 'Việtnam'),
			('zh', 'Chinese'    , '.', ',', '中文'),
			('ar', 'Arabic'     , '٫‎', '٬', 'العربية'),
			('pt', 'Portuguese' , ',', '.', 'Português'),
			('el', 'Greek'      , ',', '.', 'Ελληνικά'),
			('it', 'Italian'    , ',', '.', 'Italiano'),
			('id', 'Indonesian' , ',', '.', 'Bahasa Indonesia'),
			('uk', 'Ukrainian'  , ',', '.', 'Українська'),
			('pl', 'Polish'     , ',', '.', 'Polski'),
			('nl', 'Dutch'      , ',', '.', 'Nederlands'),
			('ko', 'Korean'     , '.', ',', '한국어'),
			('he', 'Hebrew'     , '.', ',', 'עברית'),
			('th', 'Thai'       , '.', ',', 'ไทย / Phasa Thai'),
			('cs', 'Czech'      , ',', '.', 'Česky'),
			('ro', 'Romanian'   , ',', '.', 'Română'),
			('sv', 'Swedish'    , ',', '.', 'Svenska'),
			('sr', 'Serbian'    , ',', '.', 'Српски'),
			('hu', 'Hungarian'  , ',', '.', 'Magyar'),
			('da', 'Danish'     , ',', '.', 'Dansk'),
			('bg', 'Bulgarian'  , ',', '.', 'Български'),
			('fi', 'Finnish'    , ',', '.', 'Suomi'),
			('sk', 'Slovak'     , ',', '.', 'Slovenčina'),
			('hr', 'Croatian'   , ',', '.', 'Hrvatski'),
			('hi', 'Hindi'      , '.', ',', 'हिन्दी'),
			('lt', 'Lithuanian' , ',', '.', 'Lietuvių'),
			('no', 'Norwegian'  , ',', '.', 'Norsk'),
			('sl', 'Slovenian'  , ',', '.', 'Slovenščina'),
			('ms', 'Malay'      , '.', ',', 'Bahasa Melayu')
		;
	]]

	query[[
	$table currency (
		currency    $currency not null primary key,
		decimals    smallint not null,
		en_name     $name not null, $uk(currency, en_name),
		symbol      $name
	);
	]]

	--https://en.wikipedia.org/wiki/List_of_circulating_currencies
	query[[
		insert ignore into currency
			(currency, decimals, en_name, symbol)
		values
			('AED', 2, 'United Arab Emirates dirham'             , 'د.إ'),
			('AFN', 2, 'Afghan afghani'                          , '؋'),
			('ALL', 2, 'Albanian lek'                            , 'L'),
			('AMD', 2, 'Armenian dram'                           , '֏'),
			('ANG', 2, 'Netherlands Antillean guilder'           , 'ƒ'),
			('AOA', 2, 'Angolan kwanza'                          , 'Kz'),
			('ARS', 2, 'Argentine peso'                          , '$'),
			('AUD', 2, 'Australian dollar'                       , '$'),
			('AWG', 2, 'Aruban florin'                           , 'ƒ'),
			('AZN', 2, 'Azerbaijani manat'                       , '₼'),
			('BAM', 2, 'Bosnia and Herzegovina convertible mark' , 'KM'),
			('BBD', 2, 'Barbadian dollar'                        , '$'),
			('BDT', 2, 'Bangladeshi taka'                        , '৳'),
			('BGN', 2, 'Bulgarian lev'                           , 'лв'),
			('BHD', 3, 'Bahraini dinar'                          , '.د.ب'),
			('BIF', 0, 'Burundian franc'                         , 'Fr'),
			('BMD', 2, 'Bermudian dollar'                        , '$'),
			('BND', 2, 'Brunei dollar'                           , '$'),
			('BOB', 2, 'Bolivian boliviano'                      , 'Bs'),
			('BRL', 2, 'Brazilian real'                          , 'R$'),
			('BSD', 2, 'Bahamian dollar'                         , '$'),
			('BTN', 2, 'Bhutanese ngultrum'                      , 'Nu'),
			('BWP', 2, 'Botswana pula'                           , 'P'),
			('BYN', 0, 'Belarusian ruble'                        , 'Br'),
			('BZD', 2, 'Belize dollar'                           , '$'),
			('CAD', 2, 'Canadian dollar'                         , '$'),
			('CDF', 2, 'Congolese franc'                         , 'Fr'),
			('CHF', 2, 'Swiss franc'                             , 'Fr'),
			('CKD', 2, 'Cook Islands dollar'                     , '$'),
			('CLP', 0, 'Chilean peso'                            , '$'),
			('CNY', 2, 'Chinese yuan'                            , '¥'),
			('COP', 2, 'Colombian peso'                          , '$'),
			('CRC', 2, 'Costa Rican colón'                       , '₡'),
			('CUP', 2, 'Cuban peso'                              , '$'),
			('CVE', 0, 'Cape Verdean escudo'                     , '$'),
			('CZK', 2, 'Czech koruna'                            , 'Kč'),
			('DJF', 0, 'Djiboutian franc'                        , 'Fr'),
			('DKK', 2, 'Danish krone'                            , 'kr'),
			('DOP', 2, 'Dominican peso'                          , 'RD$'),
			('DZD', 2, 'Algerian dinar'                          , 'د.ج'),
			('EGP', 2, 'Egyptian pound'                          , 'ج.م'),
			('ERN', 2, 'Eritrean nakfa'                          , 'Nfk'),
			('ETB', 2, 'Ethiopian birr'                          , 'Br'),
			('EUR', 2, 'Euro'                                    , '€'),
			('FJD', 2, 'Fijian dollar'                           , '$'),
			('FKP', 2, 'Falkland Islands pound'                  , '£'),
			('FOK', 2, 'Faroese króna'                           , 'kr'),
			('GBP', 2, 'British pound'                           , '£'),
			('GEL', 2, 'Georgian lari'                           , '₾'),
			('GGP', 2, 'Guernsey pound'                          , '£'),
			('GHS', 2, 'Ghanaian cedi'                           , '₵'),
			('GIP', 2, 'Gibraltar pound'                         , '£'),
			('GMD', 2, 'Gambian dalasi'                          , 'D'),
			('GNF', 0, 'Guinean franc'                           , 'Fr'),
			('GTQ', 2, 'Guatemalan quetzal'                      , 'Q'),
			('GYD', 2, 'Guyanese dollar'                         , '$'),
			('HKD', 2, 'Hong Kong dollar'                        , '$'),
			('HNL', 2, 'Honduran lempira'                        , 'L'),
			('HRK', 2, 'Croatian kuna'                           , 'kn'),
			('HTG', 2, 'Haitian gourde'                          , 'G'),
			('HUF', 2, 'Hungarian forint'                        , 'Ft'),
			('IDR', 2, 'Indonesian rupiah'                       , 'Rp'),
			('ILS', 2, 'Israeli new shekel'                      , '₪'),
			('IMP', 2, 'Manx pound'                              , '£'),
			('INR', 2, 'Indian rupee'                            , '₹'),
			('IQD', 3, 'Iraqi dinar'                             , 'ع.د'),
			('IRR', 0, 'Iranian rial'                            , '﷼'),
			('ISK', 0, 'Icelandic króna'                         , 'kr'),
			('JEP', 2, 'Jersey pound'                            , '£'),
			('JMD', 2, 'Jamaican dollar'                         , '$'),
			('JOD', 3, 'Jordanian dinar'                         , 'د.ا'),
			('JPY', 0, 'Japanese yen'                            , '¥'),
			('KES', 2, 'Kenyan shilling'                         , 'Sh'),
			('KGS', 2, 'Kyrgyzstani som'                         , 'с'),
			('KHR', 2, 'Cambodian riel'                          , '៛'),
			('KID', 2, 'Kiribati dollar'                         , '$'),
			('KMF', 0, 'Comorian franc'                          , 'Fr'),
			('KPW', 0, 'North Korean won'                        , '₩'),
			('KRW', 0, 'South Korean won'                        , '₩'),
			('KWD', 3, 'Kuwaiti dinar'                           , 'د.ك'),
			('KYD', 2, 'Cayman Islands dollar'                   , '$'),
			('KZT', 2, 'Kazakhstani tenge'                       , '₸'),
			('LAK', 0, 'Lao kip'                                 , '₭'),
			('LBP', 0, 'Lebanese pound'                          , 'ل.ل'),
			('LKR', 2, 'Sri Lankan rupee'                        , 'Rs'),
			('LRD', 2, 'Liberian dollar'                         , '$'),
			('LSL', 2, 'Lesotho loti'                            , 'L'),
			('LYD', 3, 'Libyan dinar'                            , 'ل.د'),
			('MAD', 2, 'Moroccan dirham'                         , 'د.م'),
			('MAD', 2, 'Moroccan dirham'                         , 'د. م'),
			('MDL', 2, 'Moldovan leu'                            , 'L'),
			('MGA', 0, 'Malagasy ariary'                         , 'Ar'),
			('MKD', 0, 'Macedonian denar'                        , 'ден'),
			('MMK', 0, 'Burmese kyat'                            , 'Ks'),
			('MNT', 2, 'Mongolian tögrög'                        , '₮'),
			('MOP', 2, 'Macanese pataca'                         , 'MOP$'),
			('MRU', 0, 'Mauritanian ouguiya'                     , 'UM'),
			('MUR', 2, 'Mauritian rupee'                         , '₨'),
			('MVR', 2, 'Maldivian rufiyaa'                       , '.ރ'),
			('MWK', 2, 'Malawian kwacha'                         , 'MK'),
			('MXN', 2, 'Mexican peso'                            , '$'),
			('MYR', 2, 'Malaysian ringgit'                       , 'RM'),
			('MZN', 2, 'Mozambican metical'                      , 'MT'),
			('NAD', 2, 'Namibian dollar'                         , '$'),
			('NGN', 2, 'Nigerian naira'                          , '₦'),
			('NIO', 2, 'Nicaraguan córdoba'                      , 'C$'),
			('NOK', 2, 'Norwegian krone'                         , 'kr'),
			('NPR', 2, 'Nepalese rupee'                          , 'रू'),
			('NZD', 2, 'New Zealand dollar'                      , '$'),
			('OMR', 3, 'Omani rial'                              , 'ر.ع'),
			('PAB', 2, 'Panamanian balboa'                       , 'B/.'),
			('PEN', 2, 'Peruvian sol'                            , 'S/.'),
			('PGK', 2, 'Papua New Guinean kina'                  , 'K'),
			('PHP', 2, 'Philippine peso'                         , '₱'),
			('PKR', 2, 'Pakistani rupee'                         , '₨'),
			('PLN', 2, 'Polish złoty'                            , 'zł'),
			('PND', 2, 'Pitcairn Islands dollar'                 , '$'),
			('PRB', 2, 'Transnistrian ruble'                     , 'р'),
			('PYG', 0, 'Paraguayan guaraní'                      , '₲'),
			('QAR', 2, 'Qatari riyal'                            , 'ر.ق'),
			('RON', 2, 'Romanian leu'                            , 'lei'),
			('RSD', 2, 'Serbian dinar'                           , 'дин'),
			('RUB', 2, 'Russian ruble'                           , '₽'),
			('RWF', 0, 'Rwandan franc'                           , 'Fr'),
			('SAR', 2, 'Saudi riyal'                             , '﷼'),
			('SBD', 2, 'Solomon Islands dollar'                  , '$'),
			('SCR', 2, 'Seychellois rupee'                       , '₨'),
			('SDG', 2, 'Sudanese pound'                          , 'ج.س'),
			('SEK', 2, 'Swedish krona'                           , 'kr'),
			('SGD', 2, 'Singapore dollar'                        , '$'),
			('SHP', 2, 'Saint Helena pound'                      , '£'),
			('SLL', 0, 'Sierra Leonean leone'                    , 'Le'),
			('SLS', 2, 'Somaliland shilling'                     , 'Sl'),
			('SOS', 2, 'Somali shilling'                         , 'Sh'),
			('SRD', 2, 'Surinamese dollar'                       , '$'),
			('SSP', 2, 'South Sudanese pound'                    , '£'),
			('STN', 0, 'São Tomé and Príncipe dobra'             , 'Db'),
			('SYP', 2, 'Syrian pound'                            , '£'),
			('SZL', 2, 'Swazi lilangeni'                         , 'L'),
			('THB', 2, 'Thai baht'                               , '฿'),
			('TJS', 2, 'Tajikistani somoni'                      , 'с'),
			('TMT', 2, 'Turkmenistan manat'                      , 'm'),
			('TND', 3, 'Tunisian dinar'                          , 'د.ت'),
			('TOP', 2, 'Tongan paʻanga'                           , 'T$'),
			('TRY', 2, 'Turkish lira'                            , '₺'),
			('TTD', 2, 'Trinidad and Tobago dollar'              , '$'),
			('TVD', 2, 'Tuvaluan dollar'                         , '$'),
			('TWD', 2, 'New Taiwan dollar'                       , '$'),
			('TZS', 2, 'Tanzanian shilling'                      , 'Sh'),
			('UAH', 2, 'Ukrainian hryvnia'                       , '₴'),
			('UGX', 2, 'Ugandan shilling'                        , 'Sh'),
			('USD', 2, 'United States dollar'                    , '$'),
			('UYU', 2, 'Uruguayan peso'                          , '$'),
			('UZS', 2, 'Uzbekistani soʻm'                         , 'Sʻ'),
			('VES', 2, 'Venezuelan bolívar soberano'             , 'Bs'),
			('VND', 0, 'Vietnamese đồng'                         , '₫'),
			('VUV', 0, 'Vanuatu vatu'                            , 'Vt'),
			('WST', 2, 'Samoan tālā'                             , 'T'),
			('XAF', 0, 'Central African CFA franc'               , 'Fr'),
			('XCD', 2, 'Eastern Caribbean dollar'                , '$'),
			('XOF', 0, 'West African CFA franc'                  , 'Fr'),
			('XPF', 0, 'CFP franc'                               , '₣'),
			('YER', 2, 'Yemeni rial'                             , '﷼'),
			('ZAR', 2, 'South African rand'                      , 'R'),
			('ZMW', 2, 'Zambian kwacha'                          , 'ZK')
		;
	]]

	query[[
	$table country (
		country     $country not null primary key,
		en_name     $name not null,
		lang        $lang not null, $fk(country, lang),
		currency    $currency, $fk(country, currency),
		imperial_system $bool
	);
	]]

	--https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes
	--https://wiki.openstreetmap.org/wiki/Nominatim/Country_Codes
	--https://unece.org/fileadmin/DAM/cefact/recommendations/bkup_htm/cocucod1.htm
	query[[
		insert ignore into country
			(country, lang, currency, imperial_system, en_name)
		values
			('AD', 'ca', 'EUR', 0, 'Andorra'),
			('AE', 'ar', 'AED', 0, 'United Arab Emirates'),
			('AF', 'fa', 'AFN', 0, 'Afghanistan'),
			('AG', 'en', 'XCD', 0, 'Antigua and Barbuda'),
			('AI', 'en', 'XCD', 0, 'Anguilla'),
			('AL', 'sq', 'ALL', 0, 'Albania'),
			('AM', 'hy', 'AMD', 0, 'Armenia'),
			('AO', 'pt', 'AOA', 0, 'Angola'),
			('AQ', 'en', null , 0, 'Antarctica'),
			('AR', 'es', 'ARS', 0, 'Argentina'),
			('AS', 'en', 'USD', 0, 'American Samoa'),
			('AT', 'de', 'EUR', 0, 'Austria'),
			('AU', 'en', 'AUD', 0, 'Australia'),
			('AW', 'nl', 'AWG', 0, 'Aruba'),
			('AX', 'sv', null , 0, 'Åland Islands'),
			('AZ', 'az', 'AZN', 0, 'Azerbaijan'),
			('BA', 'bs', 'BAM', 0, 'Bosnia and Herzegovina'),
			('BB', 'en', 'BBD', 0, 'Barbados'),
			('BD', 'bn', 'BDT', 0, 'Bangladesh'),
			('BE', 'nl', 'EUR', 0, 'Belgium'),
			('BF', 'fr', 'XOF', 0, 'Burkina Faso'),
			('BG', 'bg', 'BGN', 0, 'Bulgaria'),
			('BH', 'ar', 'BHD', 0, 'Bahrain'),
			('BI', 'fr', 'BIF', 0, 'Burundi'),
			('BJ', 'fr', 'XOF', 0, 'Benin'),
			('BL', 'fr', null , 0, 'Saint Barthélemy'),
			('BM', 'en', 'BMD', 0, 'Bermuda'),
			('BN', 'ms', 'BND', 0, 'Brunei Darussalam'),
			('BO', 'es', 'BOB', 0, 'Bolivia'),
			('BQ', 'nl', null , 0, 'Bonaire'),
			('BR', 'pt', 'BRL', 0, 'Brazil'),
			('BS', 'en', 'BSD', 0, 'Bahamas'),
			('BT', 'dz', 'INR', 0, 'Bhutan'),
			('BV', 'no', 'NOK', 0, 'Bouvet Island'),
			('BW', 'en', 'BWP', 0, 'Botswana'),
			('BY', 'be', 'BYN', 0, 'Belarus'),
			('BZ', 'en', 'BZD', 0, 'Belize'),
			('CA', 'en', 'CAD', 0, 'Canada'),
			('CC', 'en', 'AUD', 0, 'Cocos Islands'),
			('CD', 'fr', 'CDF', 0, 'Congo, the Democratic Republic of the'),
			('CF', 'fr', 'XAF', 0, 'Central African Republic'),
			('CG', 'fr', 'XAF', 0, 'Congo'),
			('CH', 'de', 'CHF', 0, 'Switzerland'),
			('CI', 'fr', 'XOF', 0, 'Côte d\'Ivoire'),
			('CK', 'en', 'NZD', 0, 'Cook Islands'),
			('CL', 'es', 'CLP', 0, 'Chile'),
			('CM', 'fr', 'XAF', 0, 'Cameroon'),
			('CN', 'zh', 'CNY', 0, 'China'),
			('CO', 'es', 'COP', 0, 'Colombia'),
			('CR', 'es', 'CRC', 0, 'Costa Rica'),
			('CU', 'es', 'CUP', 0, 'Cuba'),
			('CV', 'pt', 'CVE', 0, 'Cape Verde'),
			('CW', 'nl', 'ANG', 0, 'Curaçao'),
			('CX', 'en', 'AUD', 0, 'Christmas Island'),
			('CY', 'el', 'EUR', 0, 'Cyprus'),
			('CZ', 'cs', 'CZK', 0, 'Czech Republic'),
			('DE', 'de', 'EUR', 0, 'Germany'),
			('DJ', 'fr', 'DJF', 0, 'Djibouti'),
			('DK', 'da', 'DKK', 0, 'Denmark'),
			('DM', 'en', 'XCD', 0, 'Dominica'),
			('DO', 'es', 'DOP', 0, 'Dominican Republic'),
			('DZ', 'ar', 'DZD', 0, 'Algeria'),
			('EC', 'es', 'USD', 0, 'Ecuador'),
			('EE', 'et', 'EUR', 0, 'Estonia'),
			('EG', 'ar', 'EGP', 0, 'Egypt'),
			('EH', 'ar', 'MAD', 0, 'Western Sahara'),
			('ER', 'ti', 'ERN', 0, 'Eritrea'),
			('ES', 'as', 'EUR', 0, 'Spain'),
			('ET', 'am', 'ETB', 0, 'Ethiopia'),
			('FI', 'fi', 'EUR', 0, 'Finland'),
			('FJ', 'en', 'FJD', 0, 'Fiji'),
			('FK', 'en', 'FKP', 0, 'Falkland Islands'),
			('FM', 'en', 'USD', 0, 'Micronesia'),
			('FO', 'fo', 'FOK', 0, 'Faroe Islands'),
			('FR', 'fr', 'EUR', 0, 'France'),
			('GA', 'fr', 'XAF', 0, 'Gabon'),
			('GB', 'en', 'GBP', 0, 'United Kingdom'),
			('GD', 'en', 'XCD', 0, 'Grenada'),
			('GE', 'ka', 'GEL', 0, 'Georgia'),
			('GF', 'fr', 'EUR', 0, 'French Guiana'),
			('GG', 'en', 'GBP', 0, 'Guernsey'),
			('GH', 'en', 'GHS', 0, 'Ghana'),
			('GI', 'en', 'GIP', 0, 'Gibraltar'),
			('GL', 'kl', 'DKK', 0, 'Greenland'),
			('GM', 'en', 'GMD', 0, 'Gambia'),
			('GN', 'fr', 'GNF', 0, 'Guinea'),
			('GP', 'fr', 'EUR', 0, 'Guadeloupe'),
			('GQ', 'es', 'XAF', 0, 'Equatorial Guinea'),
			('GR', 'el', 'EUR', 0, 'Greece'),
			('GS', 'en', null , 0, 'South Georgia and the South Sandwich Islands'),
			('GT', 'es', 'GTQ', 0, 'Guatemala'),
			('GU', 'en', 'USD', 0, 'Guam'),
			('GW', 'pt', 'XOF', 0, 'Guinea-Bissau'),
			('GY', 'en', 'GYD', 0, 'Guyana'),
			('HK', 'zh', 'HKD', 0, 'Hong Kong'),
			('HM', 'en', 'AUD', 0, 'Heard Island and McDonald Islands'),
			('HN', 'es', 'HNL', 0, 'Honduras'),
			('HR', 'hr', 'HRK', 0, 'Croatia'),
			('HT', 'fr', 'HTG', 0, 'Haiti'),
			('HU', 'hu', 'HUF', 0, 'Hungary'),
			('ID', 'id', 'IDR', 0, 'Indonesia'),
			('IE', 'en', 'EUR', 0, 'Ireland'),
			('IL', 'he', 'ILS', 0, 'Israel'),
			('IM', 'en', 'GBP', 0, 'Isle of Man'),
			('IN', 'hi', 'INR', 0, 'India'),
			('IO', 'en', 'USD', 0, 'British Indian Ocean Territory'),
			('IQ', 'ar', 'IQD', 0, 'Iraq'),
			('IR', 'fa', 'IRR', 0, 'Iran'),
			('IS', 'is', 'ISK', 0, 'Iceland'),
			('IT', 'it', 'EUR', 0, 'Italy'),
			('JE', 'en', 'GBP', 0, 'Jersey'),
			('JM', 'en', 'JMD', 0, 'Jamaica'),
			('JO', 'ar', 'JOD', 0, 'Jordan'),
			('JP', 'ja', 'JPY', 0, 'Japan'),
			('KE', 'sw', 'KES', 0, 'Kenya'),
			('KG', 'ky', 'KGS', 0, 'Kyrgyzstan'),
			('KH', 'km', 'KHR', 0, 'Cambodia'),
			('KI', 'en', 'AUD', 0, 'Kiribati'),
			('KM', 'ar', 'KMF', 0, 'Comoros'),
			('KN', 'en', 'XCD', 0, 'Saint Kitts and Nevis'),
			('KP', 'ko', 'KPW', 0, 'Korea, North'),
			('KR', 'ko', 'KRW', 0, 'Korea, South'),
			('KW', 'ar', 'KWD', 0, 'Kuwait'),
			('KY', 'en', 'KYD', 0, 'Cayman Islands'),
			('KZ', 'kk', 'KZT', 0, 'Kazakhstan'),
			('LA', 'lo', 'LAK', 0, 'Lao'),
			('LB', 'ar', 'LBP', 0, 'Lebanon'),
			('LC', 'en', 'XCD', 0, 'Saint Lucia'),
			('LI', 'de', 'CHF', 0, 'Liechtenstein'),
			('LK', 'si', 'LKR', 0, 'Sri Lanka'),
			('LR', 'en', 'LRD', 1, 'Liberia'),
			('LS', 'en', 'ZAR', 0, 'Lesotho'),
			('LT', 'lt', 'EUR', 0, 'Lithuania'),
			('LU', 'lb', 'EUR', 0, 'Luxembourg'),
			('LV', 'lv', 'EUR', 0, 'Latvia'),
			('LY', 'ar', 'LYD', 0, 'Libya'),
			('MA', 'fr', 'MAD', 0, 'Morocco'),
			('MC', 'fr', 'EUR', 0, 'Monaco'),
			('MD', 'ro', 'MDL', 0, 'Moldova'),
			('ME', 'sr', 'EUR', 0, 'Montenegro'),
			('MF', 'fr', null , 0, 'Saint Martin (French part)'),
			('MG', 'mg', 'MGA', 0, 'Madagascar'),
			('MH', 'en', 'USD', 0, 'Marshall Islands'),
			('MK', 'mk', 'MKD', 0, 'Macedonia'),
			('ML', 'fr', 'XOF', 0, 'Mali'),
			('MM', 'my', 'MMK', 1, 'Myanmar'),
			('MN', 'mn', 'MNT', 0, 'Mongolia'),
			('MO', 'zh', 'MOP', 0, 'Macao'),
			('MP', 'en', 'USD', 0, 'Northern Mariana Islands'),
			('MQ', 'fr', 'EUR', 0, 'Martinique'),
			('MR', 'ar', 'MRU', 0, 'Mauritania'),
			('MS', 'en', 'XCD', 0, 'Montserrat'),
			('MT', 'mt', 'EUR', 0, 'Malta'),
			('MU', 'mf', 'MUR', 0, 'Mauritius'),
			('MV', 'dv', 'MVR', 0, 'Maldives'),
			('MW', 'en', 'MWK', 0, 'Malawi'),
			('MX', 'es', 'MXN', 0, 'Mexico'),
			('MY', 'ms', 'MYR', 0, 'Malaysia'),
			('MZ', 'pt', 'MZN', 0, 'Mozambique'),
			('NA', 'en', 'ZAR', 0, 'Namibia'),
			('NC', 'fr', 'XPF', 0, 'New Caledonia'),
			('NE', 'fr', 'XOF', 0, 'Niger'),
			('NF', 'en', 'AUD', 0, 'Norfolk Island'),
			('NG', 'en', 'NGN', 0, 'Nigeria'),
			('NI', 'es', 'NIO', 0, 'Nicaragua'),
			('NL', 'nl', 'EUR', 0, 'Netherlands'),
			('NO', 'nb', 'NOK', 0, 'Norway'),
			('NP', 'ne', 'NPR', 0, 'Nepal'),
			('NR', 'na', 'AUD', 0, 'Nauru'),
			('NU', 'ni', 'NZD', 0, 'Niue'),
			('NZ', 'mi', 'NZD', 0, 'New Zealand'),
			('OM', 'ar', 'OMR', 0, 'Oman'),
			('PA', 'es', 'USD', 0, 'Panama'),
			('PE', 'es', 'PEN', 0, 'Peru'),
			('PF', 'fr', 'XPF', 0, 'French Polynesia'),
			('PG', 'en', 'PGK', 0, 'Papua New Guinea'),
			('PH', 'en', 'PHP', 0, 'Philippines'),
			('PK', 'en', 'PKR', 0, 'Pakistan'),
			('PL', 'pl', 'PLN', 0, 'Poland'),
			('PM', 'fr', 'EUR', 0, 'Saint Pierre and Miquelon'),
			('PN', 'en', 'NZD', 0, 'Pitcairn'),
			('PR', 'es', 'USD', 0, 'Puerto Rico'),
			('PS', 'ar', null , 0, 'Palestine'),
			('PT', 'pt', 'EUR', 0, 'Portugal'),
			('PW', 'en', 'USD', 0, 'Palau'),
			('PY', 'es', 'PYG', 0, 'Paraguay'),
			('QA', 'ar', 'QAR', 0, 'Qatar'),
			('RE', 'fr', 'EUR', 0, 'Réunion'),
			('RO', 'ro', 'RON', 0, 'Romania'),
			('RS', 'sr', 'RSD', 0, 'Serbia'),
			('RU', 'ru', 'RUB', 0, 'Russian Federation'),
			('RW', 'rw', 'RWF', 0, 'Rwanda'),
			('SA', 'ar', 'SAR', 0, 'Saudi Arabia'),
			('SB', 'en', 'SBD', 0, 'Solomon Islands'),
			('SC', 'fr', 'SCR', 0, 'Seychelles'),
			('SD', 'ar', 'SDG', 0, 'Sudan'),
			('SE', 'sv', 'SEK', 0, 'Sweden'),
			('SG', 'zh', 'BND', 0, 'Singapore'),
			('SH', 'en', 'SHP', 0, 'Saint Helena'),
			('SI', 'sl', 'EUR', 0, 'Slovenia'),
			('SJ', 'no', 'NOK', 0, 'Svalbard and Jan Mayen'),
			('SK', 'sk', 'EUR', 0, 'Slovakia'),
			('SL', 'en', 'SLL', 0, 'Sierra Leone'),
			('SM', 'it', 'EUR', 0, 'San Marino'),
			('SN', 'fr', 'XOF', 0, 'Senegal'),
			('SO', 'so', 'SOS', 0, 'Somalia'),
			('SR', 'nl', 'SRD', 0, 'Suriname'),
			('SS', 'en', 'SSP', 0, 'South Sudan'),
			('ST', 'pt', 'STD', 0, 'Sao Tome and Principe'),
			('SV', 'es', 'USD', 0, 'El Salvador'),
			('SX', 'nl', null , 0, 'Sint Maarten (Dutch part)'),
			('SY', 'ar', 'SYP', 0, 'Syria'),
			('SZ', 'en', 'SZL', 0, 'Swaziland'),
			('TC', 'en', 'USD', 0, 'Turks and Caicos Islands'),
			('TD', 'fr', 'XAF', 0, 'Chad'),
			('TF', 'fr', 'EUR', 0, 'French Southern Territories'),
			('TG', 'fr', 'XOF', 0, 'Togo'),
			('TH', 'th', 'THB', 0, 'Thailand'),
			('TJ', 'tg', 'TJS', 0, 'Tajikistan'),
			('TK', 'tk', 'NZD', 0, 'Tokelau'),
			('TL', 'pt', 'USD', 0, 'Timor-Leste'),
			('TM', 'tk', 'TMT', 0, 'Turkmenistan'),
			('TN', 'ar', 'TND', 0, 'Tunisia'),
			('TO', 'en', 'TOP', 0, 'Tonga'),
			('TR', 'tr', 'TRY', 0, 'Turkey'),
			('TT', 'en', 'TTD', 0, 'Trinidad and Tobago'),
			('TV', 'en', 'AUD', 0, 'Tuvalu'),
			('TW', 'zh', 'TWD', 0, 'Taiwan'),
			('TZ', 'sw', 'TZS', 0, 'Tanzania'),
			('UA', 'uk', 'UAH', 0, 'Ukraine'),
			('UG', 'en', 'UGX', 0, 'Uganda'),
			('UM', 'en', 'USD', 0, 'United States Minor Outlying Islands'),
			('US', 'en', 'USD', 1, 'United States'),
			('UY', 'es', 'UYU', 0, 'Uruguay'),
			('UZ', 'uz', 'UZS', 0, 'Uzbekistan'),
			('VA', 'it', 'EUR', 0, 'Vatican'),
			('VC', 'en', 'XCD', 0, 'Saint Vincent and the Grenadines'),
			('VE', 'es', 'VEB', 0, 'Venezuela'),
			('VG', 'en', 'USD', 0, 'Virgin Islands, British'),
			('VI', 'en', 'USD', 0, 'Virgin Islands, U.S.'),
			('VN', 'vi', 'VND', 0, 'Viet Nam'),
			('VU', 'bi', 'VUV', 0, 'Vanuatu'),
			('WF', 'fr', 'XPF', 0, 'Wallis and Futuna'),
			('WS', 'sm', 'WST', 0, 'Samoa'),
			('YE', 'ar', 'YER', 0, 'Yemen'),
			('YT', 'fr', 'EUR', 0, 'Mayotte'),
			('ZA', 'en', 'ZAR', 0, 'South Africa'),
			('ZM', 'en', 'ZMW', 0, 'Zambia'),
			('ZW', 'en', 'ZWB', 0, 'Zimbabwe')
		;
	]]

end
