return {
	root={
		background_color=255,
		background_color_stop_count=2,
		background_type=1,
		border_color_bottom=4294967078,
		border_color_left=4294967078,
		border_color_right=4294967078,
		border_color_top=4294967078,
		clip_content=true,
		h=936,
		layout_type=1,
		min_cw=619.5,
		padding_bottom=16.5,
		padding_left=16.5,
		padding_right=16.5,
		padding_top=16.5,
		rotation_cx=304,
		rotation_cy=418.5,
		shadow_count=1,
		shadows={
			{
				shadow_blur=14,
				shadow_color=640034559
			}
		},
		span_count=4,
		text='Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aenean vel elit scelerisque mauris pellentesque. Urna porttitor rhoncus dolor purus non enim praesent. Bibendum ut tristique et egestas quis ipsum. Risus in hendrerit gravida rutrum quisque non tellus orci ac. Etiam erat velit scelerisque in. Ut pharetra sit amet aliquam. Porttitor massa id neque aliquam vestibulum. Metus dictum at tempor commodo ullamcorper. Ut venenatis tellus in metus. Massa placerat duis ultricies lacus sed turpis tincidunt id aliquet. Et netus et malesuada fames ac turpis egestas sed. Tincidunt id aliquet risus feugiat in ante. Dolor sit amet consectetur adipiscing elit duis tristique sollicitudin nibh.\r\n\r\nJusto nec ultrices dui sapien eget mi proin. Molestie a iaculis at erat pellentesque adipiscing commodo elit at. Ac feugiat sed lectus vestibulum mattis ullamcorper. Varius vel pharetra vel turpis nunc eget lorem dolor sed. Varius duis at consectetur lorem donec massa sapien faucibus. Id ornare arcu odio ut. Ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Ultricies tristique nulla aliquet enim tortor at auctor. Neque convallis a cras semper. Blandit cursus risus at ultrices mi tempus imperdiet nulla. Aliquam sem et tortor consequat id porta.\r\n\r\nEgestas egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate. Eget nunc lobortis mattis aliquam faucibus purus. Velit sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Elit sed vulputate mi sit amet mauris commodo quis imperdiet. Magnis dis parturient montes nascetur ridiculus mus. Nunc consequat interdum varius sit amet mattis vulputate. Eget lorem dolor sed viverra ipsum. Est placerat in egestas erat imperdiet sed. Amet massa vitae tortor condimentum lacinia quis vel eros. Amet risus nullam eget felis. Et odio pellentesque diam volutpat commodo sed egestas egestas. Lorem ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Sed enim ut sem viverra aliquet eget sit amet tellus. Vulputate ut pharetra sit amet aliquam id diam maecenas ultricies.\r\n\r\nFelis imperdiet proin fermentum leo vel orci. Et egestas quis ipsum suspendisse ultrices gravida dictum fusce. Nisl tincidunt eget nullam non. Nisi porta lorem mollis aliquam ut porttitor leo. Nisi porta lorem mollis aliquam ut. Ornare aenean euismod elementum nisi. Sagittis aliquam malesuada bibendum arcu vitae elementum curabitur. Nec tincidunt praesent semper feugiat nibh sed pulvinar. Tristique senectus et netus et malesuada. Etiam sit amet nisl purus in mollis nunc.\r\n\r\nEu feugiat pretium nibh ipsum consequat nisl. Sit amet aliquam id diam. Metus dictum at tempor commodo ullamcorper a lacus vestibulum. Nunc lobortis mattis aliquam faucibus purus. Lacinia at quis risus sed vulputate. Sagittis nisl rhoncus mattis rhoncus urna. Pellentesque elit eget gravida cum. Diam volutpat commodo sed egestas egestas. Faucibus purus in massa tempor nec feugiat nisl pretium fusce. Quis auctor elit sed vulputate mi sit amet. Duis convallis convallis tellus id interdum. Cursus metus aliquam eleifend mi.\r\n\r\nWho do you think, the Libyans. Ohh, no. Now, of course not, Biff, now, I wouldn\'t want that to happen. Let him go, Biff, you\'re drunk. Wait a minute, wait a minute. 1:15 in the morning?\r\n\r\nIt\'s already mutated into human form, shoot it. Look, there\'s a rhythmic ceremonial ritual coming up. You want it, you know you want it, and you know you want me to give it to you. Oh, great scott. You get the cable, I\'ll throw the rope down to you. I\'ll be at my grandma\'s. Here, let me give you the number. Bye.\r\n\r\nI have to tell you about the future. That was so stupid, Grandpa hit him with the car. What, right here right now in the cafeteria? What is she said no? I don\'t know if I could take that kind of rejection. Besides, I think she\'d rather go with somebody else. We never would have fallen in love. I said the keys are in here.\r\n',
		text_align_x=4,
		text_align_y=1,
		text_cursor_count=1,
		text_cursors={
			{
				text_cursor_offset=74,
				text_cursor_sel_offset=74,
				text_cursor_x=421.5
			}
		},
		text_spans={
			{
				span_font='OpenSans-Regular.ttf',
				span_font_size=12,
				span_opacity=2
			},
			{
				span_font='Amiri-Regular.ttf',
				span_font_size=12,
				span_offset=275,
				span_opacity=2
			},
			{
				span_font='OpenSans-Regular.ttf',
				span_font_size=12,
				span_offset=421,
				span_opacity=2
			},
			{
				span_font='Amiri-Regular.ttf',
				span_font_size=12,
				span_offset=1352,
				span_opacity=2
			}
		},
		w=652.5,
		x=100,
		y=39
	},
	selected_layer_path={
	},
	tab='Position'
}