return {
	root={
		border_width_bottom=1,
		border_width_left=1,
		border_width_right=1,
		border_width_top=1,
		h=300,
		span_count=3,
		text='ffi',
		text_cursor_count=1,
		text_cursors={
			{
				text_cursor_offset=3,
				text_cursor_sel_offset=3,
				text_cursor_x=277
			}
		},
		text_spans={
			{
				span_font='Amiri-Regular.ttf',
				span_font_size=91,
				span_text_color=2492765439
			},
			{
				span_font='Amiri-Regular.ttf',
				span_font_size=91,
				span_offset=1,
				span_text_color=132441343
			},
			{
				span_font='Amiri-Regular.ttf',
				span_font_size=91,
				span_offset=2,
				span_text_color=1499027967
			}
		},
		w=500,
		x=100,
		y=100
	},
	selected_layer_path={
	},
	tab='Text'
}