S('years', '{0} ani')
S('months', '{0} luni')
S('days', '{0} zile')
S('hours', '{0} ore')
S('minutes', '{0} minute')
S('one_minute', '1 minut')

S('time_ago', 'acum {0}')
S('in_time', 'in {0}')

S('from', 'din')
S('today', 'Azi')
S('date_format', '{day} {month} {year} {time}')

S('jan', 'Ian')
S('feb', 'Feb')
S('mar', 'Mar')
S('apr', 'Apr')
S('may', 'Mai')
S('jun', 'Iun')
S('jul', 'Iul')
S('aug', 'Aug')
S('sep', 'Sep')
S('oct', 'Oct')
S('nov', 'Noi')
S('dec', 'Dec')

S('january', 'Ianuarie')
S('february', 'Februarie')
S('mars', 'Martie')
S('april', 'Aprilie')
S('may', 'Mai')
S('june', 'Iunie')
S('july', 'Iulie')
S('august', 'August')
S('september', 'Septembrie')
S('october', 'Octombrie')
S('november', 'Noiembrie')
S('december', 'Decembrie')

S('home', 'acasa')
S('store', 'magazin')

S('order_status_new', 'nepreluata')
S('order_status_open', 'preluata')
S('order_status_secured', 'obtinuta')
S('order_status_shipped', 'trimisa')
S('order_status_canceled', 'anulata')
S('order_status_returned', 'returnata')

S('move_here', 'Muta-l aici')
S('remove', 'Sterge')
S('price', '{0} Lei')
S('next_page', 'pagina urmatoare')
S('previous_page', 'pagina anterioara')

S('na', '<span class=notavailable>Nedisponibil</span>')
S('not_available', 'Nedisponibil')
S('out_of_stock', 'Lipsa stoc')
S('plenty_in_stock', '<b>In stoc</b>')
S('low_stock', '<b>Doar {0} bucati</b> in stoc')
S('in_stock', '<b>{0} bucati</b> in stoc')
S('not_available_msg', 'Combinatie nedisponibila.\nTe rugam alege alta combinatie.')

S('login_failed', 'Nu am reusit sa te logam.')
S('email_required_error', 'Completeaza email-ul')
S('email_format_error', 'Incearca cu formatul ceva@altceva.com')
S('pass_required_error', 'Adauga o parola')
S('pass_format_error', 'Adauga cel putin {0} caractere')
S('name_required_error', 'Completeaza numele')
S('phone_required_error', 'Adauga numarul de telefon')
S('phone_invalid_error', 'Numar de telefon incorect')
S('street_required_error', 'Completeaza adresa')
S('city_required_error', 'Nu uita sa completezi orasul')
S('county_required_error', 'Nu uita sa completezi judetul')
S('order_error', 'Nu am reusit sa plasam comanda.\nTe rugam sa incerci din nou sau sa ne contactezi direct.')

S('server_error', 'S-a produs o eroare.<br>Te rugam sa incerci din nou<br>sau sa ne contactezi.')
S('login_error_email_taken', 'Email deja inregistrat')
S('login_error_user_pass', 'Email sau parola incorecta')

S('changes_saved', 'Modificarile au fost salvate')
S('update_failed', 'S-a produs o eroare.<br>Modificarile NU au fost salvate')
S('added_to_order', 'Produsul a fost adaugat la comanda')

S('subscribe_ok', 'Iti multumim!<br>Te vom tine la curent cu ofertele noastre.')
S('subscribe_error', 'S-a produs o eroare.<br>Te rugam sa incerci din nou.')
